export interface TarotCard {
  id: number;
  name: string;
  number: number;
  arcana: 'Major' | 'Minor';
  suit: 'Cups' | 'Wands' | 'Swords' | 'Pentacles' | null;
  imageEmoji: string;
  keywords: string[];
  generalMeaning: string;
  loveMeaning: string;
  careerMeaning: string;
  familyMeaning: string;
  healthMeaning: string;
  futureMeaning: string;
  spiritualMeaning: string;
  advice: string;
  positiveMeaning: string;
  negativeMeaning: string;
  reversedMeaning: string;
  warning: string;
  element: string;
  planet: string;
  zodiac: string;
  difficulty: number;
  memoryLevel: 'easy' | 'medium' | 'hard';
}

export const tarotCards: TarotCard[] = [
  // MAJOR ARCANA (22 cards)
  {
    id: 0,
    name: 'The Fool',
    number: 0,
    arcana: 'Major',
    suit: null,
    imageEmoji: '🤡',
    keywords: ['new beginning', 'innocence', 'spontaneity', 'blindness', 'risk'],
    generalMeaning: 'Khởi đầu cuộc hành trình mới, sự tin tưởng tuyệt đối vào tương lai.',
    loveMeaning: 'Tình yêu mới, sự phiêu lưu lãng mạn trong tình cảm.',
    careerMeaning: 'Bắt đầu công việc mới, dự án mạo hiểm cần kế hoạch cụ thể.',
    familyMeaning: 'Thay đổi gia đình, năng lượng tuổi trẻ phát triển.',
    healthMeaning: 'Năng lượng tươi mới, cần chú ý đến an toàn.',
    futureMeaning: 'Những khả năng vô tận, nhưng cần chuẩn bị tốt.',
    spiritualMeaning: 'Sự khởi đầu con đường tâm linh, tin tưởng tuyệt đối.',
    advice: 'Dùng trí tuệ để hướng dẫn sự tin tưởng của bạn.',
    positiveMeaning: 'Tự do, phiêu lưu, khởi đầu mới, sự ngây thơ tích cực.',
    negativeMeaning: 'Bất cẩn, vô trách nhiệm, quyết định vội vàng.',
    reversedMeaning: 'Cẩn trọng quá mức, bỏ lỡ cơ hội, bỏ qua cuộc sống.',
    warning: 'Cân bằng phiêu lưu và trách nhiệm.',
    element: 'Air',
    planet: 'Uranus',
    zodiac: 'All',
    difficulty: 2,
    memoryLevel: 'easy',
  },
  {
    id: 1,
    name: 'The Magician',
    number: 1,
    arcana: 'Major',
    suit: null,
    imageEmoji: '🎩',
    keywords: ['manifestation', 'resourcefulness', 'power', 'inspired action'],
    generalMeaning: 'Khả năng biến đổi, sử dụng hết nguồn lực, quyền lực tạo kết quả.',
    loveMeaning: 'Sự hấp dẫn, cần lưu ý đến sự chân thật tình cảm.',
    careerMeaning: 'Tận dụng kỹ năng, thành công thông qua hành động quyết định.',
    familyMeaning: 'Thành viên thông minh, khéo léo, hoặc thao túng.',
    healthMeaning: 'Sức khỏe tốt, khả năng tự chữa lành.',
    futureMeaning: 'Khả năng kiểm soát tình huống, thành công qua kỹ năng.',
    spiritualMeaning: 'Kết nối vật chất và tinh thần, khả năng biến đổi bên trong.',
    advice: 'Tin vào sức mạnh và sử dụng nó một cách đạo đức.',
    positiveMeaning: 'Tạo hiệu ứng, khả năng, tập trung, quyết định.',
    negativeMeaning: 'Thao túng, gian dối, dối trá, lạm dụng quyền lực.',
    reversedMeaning: 'Thiếu tập trung, mất sức mạnh, thực tế bị che giấu.',
    warning: 'Sử dụng quyền lực một cách có trách nhiệm.',
    element: 'Air',
    planet: 'Mercury',
    zodiac: 'Gemini',
    difficulty: 2,
    memoryLevel: 'easy',
  },
  {
    id: 2,
    name: 'The High Priestess',
    number: 2,
    arcana: 'Major',
    suit: null,
    imageEmoji: '👑',
    keywords: ['intuition', 'sacred knowledge', 'subconscious', 'femininity'],
    generalMeaning: 'Trí tuệ ẩn giấu, intuition sâu, bí mật chưa tiết lộ.',
    loveMeaning: 'Bí mật lớn, cần khám phá cảm xúc thực sự.',
    careerMeaning: 'Trực giác công việc, cần lắng nghe tiếng nói bên trong.',
    familyMeaning: 'Người phụ nữ bí mật, tri thức ẩn giấu.',
    healthMeaning: 'Lắng nghe cơ thể, sức khỏe tinh thần.',
    futureMeaning: 'Bí mật sẽ bị tiết lộ, khám phá điều quan trọng.',
    spiritualMeaning: 'Kết nối tâm linh nữ tính, trực giác cao.',
    advice: 'Lắng nghe tiếng nói bên trong, tin tưởng trực giác.',
    positiveMeaning: 'Trực giác, thiêng liêng, tri thức ẩn, bí ẩn.',
    negativeMeaning: 'Lạnh lùng, bí mật quá, thiếu giao tiếp.',
    reversedMeaning: 'Tiết lộ bí mật, quá tự tin, bỏ qua trực giác.',
    warning: 'Đừng bỏ qua cảnh báo từ trực giác.',
    element: 'Water',
    planet: 'Moon',
    zodiac: 'Cancer',
    difficulty: 2,
    memoryLevel: 'easy',
  },
  {
    id: 3,
    name: 'The Empress',
    number: 3,
    arcana: 'Major',
    suit: null,
    imageEmoji: '👸',
    keywords: ['femininity', 'beauty', 'abundance', 'nature', 'fertility'],
    generalMeaning: 'Phong phú, tiền bạc, sáng tạo, sức mạnh nữ tính.',
    loveMeaning: 'Tình yêu sâu đậm, sự lãng mạn thực sự.',
    careerMeaning: 'Sáng tạo, thành công kinh doanh, lãnh đạo nữ.',
    familyMeaning: 'Người mẹ yêu thương, sự chăm sóc gia đình.',
    healthMeaning: 'Sức khỏe tốt, sự cân bằng nội tiết.',
    futureMeaning: 'Phong phú, sáng tạo, hạnh phúc gia đình.',
    spiritualMeaning: 'Sức mạnh nữ tính, kết nối thiên nhiên.',
    advice: 'Tôn trọng sức mạnh nữ tính của bạn.',
    positiveMeaning: 'Hạnh phúc, sáng tạo, phong phú, thiên nhiên.',
    negativeMeaning: 'Vô sinh, thiếu sáng tạo, cô lập.',
    reversedMeaning: 'Thiếu phong phú, sáng tạo bị chặn.',
    warning: 'Chấp nhận sự đổi thay và phát triển bên trong.',
    element: 'Earth',
    planet: 'Venus',
    zodiac: 'Taurus',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 4,
    name: 'The Emperor',
    number: 4,
    arcana: 'Major',
    suit: null,
    imageEmoji: '👑',
    keywords: ['authority', 'establishment', 'structure', 'control', 'father'],
    generalMeaning: 'Quyền lực, cấu trúc, quy tắc, lãnh đạo nam tính.',
    loveMeaning: 'Mối quan hệ nghiêm túc, người đàn ông mạnh mẽ.',
    careerMeaning: 'Thành công, lãnh đạo, quyền lực, kỷ luật công việc.',
    familyMeaning: 'Người cha, quyền lực nam, cấu trúc gia đình.',
    healthMeaning: 'Sức khỏe tốt, quyết định y tế công bằng.',
    futureMeaning: 'Cấu trúc, ổn định, thành công qua kỷ luật.',
    spiritualMeaning: 'Sức mạnh nam tính, kiểm soát bên trong ý chí.',
    advice: 'Cân bằng kiểm soát và linh hoạt.',
    positiveMeaning: 'Thành công, quyền lực, lãnh đạo, kỷ luật.',
    negativeMeaning: 'Độc tài, giận dữ, kiểm soát quá mức.',
    reversedMeaning: 'Mất quyền lực, yếu đuối, mất kiểm soát.',
    warning: 'Sử dụng quyền lực một cách công bằng.',
    element: 'Fire',
    planet: 'Aries',
    zodiac: 'Aries',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 5,
    name: 'The Hierophant',
    number: 5,
    arcana: 'Major',
    suit: null,
    imageEmoji: '⛪',
    keywords: ['spirituality', 'tradition', 'conformity', 'education', 'belief'],
    generalMeaning: 'Truyền thống, tôn giáo, cấu trúc tinh thần, sư thầy.',
    loveMeaning: 'Hôn nhân truyền thống, cam kết lâu dài.',
    careerMeaning: 'Giáo dục, tôn giáo, công việc chính thức.',
    familyMeaning: 'Truyền thống gia đình, lão tiền bối.',
    healthMeaning: 'Y học chính thống, phương pháp truyền thống.',
    futureMeaning: 'Tuân theo truyền thống, cam kết dài hạn.',
    spiritualMeaning: 'Kết nối tôn giáo, khai sáng qua học hành.',
    advice: 'Cân bằng truyền thống với sự cải tiến.',
    positiveMeaning: 'Giáo dục, tinh thần, hôn nhân, kỹ năng.',
    negativeMeaning: 'Giáo điều, cứng nhắc, tuân phục mù quang.',
    reversedMeaning: 'Phản kháng truyền thống, tự do tâm linh.',
    warning: 'Không bác bỏ hoàn toàn bài học quá khứ.',
    element: 'Earth',
    planet: 'Taurus',
    zodiac: 'Taurus',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 6,
    name: 'The Lovers',
    number: 6,
    arcana: 'Major',
    suit: null,
    imageEmoji: '💞',
    keywords: ['love', 'harmony', 'values', 'choice', 'relationships'],
    generalMeaning: 'Tình yêu, hòa hợp, lựa chọn quan trọng, giá trị chân thật.',
    loveMeaning: 'Tình yêu sâu sắc, hòa hợp, quyết định tình cảm.',
    careerMeaning: 'Hợp tác, kết nối nghề nghiệp, lựa chọn sự nghiệp.',
    familyMeaning: 'Liên kết gia đình, tình yêu huyết thống.',
    healthMeaning: 'Cân bằng cơ thể, sức khỏe toàn diện.',
    futureMeaning: 'Tình yêu, lựa chọn quan trọng, hài hòa.',
    spiritualMeaning: 'Kết nối linh hồn, tình yêu vũ trụ.',
    advice: 'Lắng nghe trái tim khi quyết định.',
    positiveMeaning: 'Tình yêu, hài hòa, kết nối, lựa chọn tốt.',
    negativeMeaning: 'Xung đột, chia tay, lựa chọn sai.',
    reversedMeaning: 'Mất kết nối, chia tay, giá trị khác nhau.',
    warning: 'Lựa chọn phải đến từ trái tim.',
    element: 'Air',
    planet: 'Gemini',
    zodiac: 'Gemini',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 7,
    name: 'The Chariot',
    number: 7,
    arcana: 'Major',
    suit: null,
    imageEmoji: '🛞',
    keywords: ['control', 'willpower', 'determination', 'discipline', 'ambition'],
    generalMeaning: 'Kiểm soát, ý chí mạnh, quyết tâm, chiến thắng.',
    loveMeaning: 'Chiến đấu vì tình yêu, quyết tâm trong quan hệ.',
    careerMeaning: 'Thành công thông qua ý chí, chiến thắng cạnh tranh.',
    familyMeaning: 'Bảo vệ gia đình, kỷ luật, quyết tâm.',
    healthMeaning: 'Sức khỏe mạnh mẽ, chiến đấu với bệnh tật.',
    futureMeaning: 'Chiến thắng, thành công qua nỗ lực.',
    spiritualMeaning: 'Kiểm soát đức tính, chiến đấu yếu tố âm.',
    advice: 'Duy trì kỷ luật cho đến khi thành công.',
    positiveMeaning: 'Chiến thắng, kiểm soát, quyết tâm, nỗ lực.',
    negativeMeaning: 'Mất kiểm soát, lao động quá mức, sai lầm.',
    reversedMeaning: 'Mất kiểm soát, hỗn loạn, thất bại.',
    warning: 'Không lạm dụng sức mạnh để kiểm soát người khác.',
    element: 'Fire',
    planet: 'Cancer',
    zodiac: 'Cancer',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 8,
    name: 'Strength',
    number: 8,
    arcana: 'Major',
    suit: null,
    imageEmoji: '💪',
    keywords: ['inner strength', 'courage', 'patience', 'control', 'compassion'],
    generalMeaning: 'Sức mạnh nội tâm, can đảm, kiên nhẫn, kiểm soát nhẹ nhàng.',
    loveMeaning: 'Tình yêu mạnh mẽ, kiên nhẫn trong quan hệ.',
    careerMeaning: 'Thành công qua kiên nhẫn, can đảm trong quyết định.',
    familyMeaning: 'Sức mạnh gia đình, kiên nhẫn với nhau.',
    healthMeaning: 'Sức mạnh cơ thể, khôi phục, kiên nhẫn.',
    futureMeaning: 'Sức mạnh vượt qua thử thách, kiên nhẫn thành công.',
    spiritualMeaning: 'Sức mạnh tinh thần, kiểm soát bản năng.',
    advice: 'Bình tĩnh và sử dụng sức mạnh nội tâm.',
    positiveMeaning: 'Sức mạnh, can đảm, kiên nhẫn, tình yêu.',
    negativeMeaning: 'Yếu đuối, mất can đảm, quá ý chí.',
    reversedMeaning: 'Thiếu can đảm, mất sức mạnh, bỏ cuộc.',
    warning: 'Sức mạnh không phải bạo lực, kiểm soát bản thân.',
    element: 'Fire',
    planet: 'Leo',
    zodiac: 'Leo',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 9,
    name: 'The Hermit',
    number: 9,
    arcana: 'Major',
    suit: null,
    imageEmoji: '🕯️',
    keywords: ['introspection', 'inner guidance', 'search', 'meditation', 'wisdom'],
    generalMeaning: 'Rút lui, tự chiêm ngưỡng, tìm kiếm lẽ thật.',
    loveMeaning: 'Cần thời gian một mình, suy ngẫm về tình yêu.',
    careerMeaning: 'Cần thời gian tư duy, khôn ngoan, công việc độc lập.',
    familyMeaning: 'Ít nói, tìm sự riêng tư, chia sẻ khôn ngoan.',
    healthMeaning: 'Cần nghỉ ngơi, suy ngẫm, chữa lành nội tâm.',
    futureMeaning: 'Thời gian tư duy, khôn ngoan sẽ đến.',
    spiritualMeaning: 'Tìm kiếm lẽ thật, khai sáng qua thiền.',
    advice: 'Cân bằng cô lập với kết nối xã hội.',
    positiveMeaning: 'Khôn ngoan, tư duy, tìm kiếm, hướng dẫn nội tâm.',
    negativeMeaning: 'Cô lập quá, tách rời xã hội, thiếu kết nối.',
    reversedMeaning: 'Trở lại xã hội, chia sẻ khôn ngoan.',
    warning: 'Tìm khôn ngoan nhưng không cô lập quá.',
    element: 'Earth',
    planet: 'Virgo',
    zodiac: 'Virgo',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 10,
    name: 'Wheel of Fortune',
    number: 10,
    arcana: 'Major',
    suit: null,
    imageEmoji: '🎡',
    keywords: ['good luck', 'karma', 'life cycles', 'destiny', 'fortune'],
    generalMeaning: 'May mắn, vận mệnh, chu kỳ cuộc sống.',
    loveMeaning: 'Vận mệnh tình yêu, thay đổi quan hệ.',
    careerMeaning: 'Thay đổi công việc, may mắn sự nghiệp.',
    familyMeaning: 'Thay đổi gia đình, vòng xoay cuộc sống.',
    healthMeaning: 'Thay đổi sức khỏe, chu kỳ chữa lành.',
    futureMeaning: 'Những thay đổi, vòng xoay sẽ quay.',
    spiritualMeaning: 'Karma, vận mệnh tinh thần.',
    advice: 'Chấp nhận chu kỳ cuộc sống.',
    positiveMeaning: 'May mắn, thay đổi tốt, vận mệnh, tiến bộ.',
    negativeMeaning: 'Không may mắn, chu kỳ xấu.',
    reversedMeaning: 'Mất may mắn, chu kỳ đảo ngược.',
    warning: 'Không mọi thứ trong tay bạn.',
    element: 'Fire',
    planet: 'Jupiter',
    zodiac: 'All',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 11,
    name: 'Justice',
    number: 11,
    arcana: 'Major',
    suit: null,
    imageEmoji: '⚖️',
    keywords: ['justice', 'fairness', 'truth', 'cause', 'accountability'],
    generalMeaning: 'Công lý, sự thật, cân bằng, trách nhiệm.',
    loveMeaning: 'Công lý tình yêu, sự thật tiết lộ.',
    careerMeaning: 'Công lý công việc, sự công bằng.',
    familyMeaning: 'Công lý gia đình, sự thật gia đình.',
    healthMeaning: 'Cân bằng sức khỏe, trách nhiệm.',
    futureMeaning: 'Công lý sẽ đến, sự thật bộc lộ.',
    spiritualMeaning: 'Karma, công lý tâm linh.',
    advice: 'Chịu trách nhiệm cho hành động.',
    positiveMeaning: 'Công lý, sự thật, cân bằng, công bằng.',
    negativeMeaning: 'Bất công, nói dối, mất cân bằng.',
    reversedMeaning: 'Bất công, sự thật bị che giấu.',
    warning: 'Sự thật sẽ bộc lộ, sống công bằng.',
    element: 'Air',
    planet: 'Libra',
    zodiac: 'Libra',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 12,
    name: 'The Hanged Man',
    number: 12,
    arcana: 'Major',
    suit: null,
    imageEmoji: '🪢',
    keywords: ['letting go', 'perspective', 'pause', 'surrender', 'restriction'],
    generalMeaning: 'Sự chân tự, thay đổi quan điểm, khoảnh dừng.',
    loveMeaning: 'Sự chân tự tình yêu, đợi chờ, thay đổi cách nhìn.',
    careerMeaning: 'Tạm dừng công việc, thay đổi quan điểm.',
    familyMeaning: 'Sự chân tự gia đình, tạm dừng xung đột.',
    healthMeaning: 'Tạm dừng, sự chân tự chữa lành.',
    futureMeaning: 'Tạm dừng, sự chân tự mới.',
    spiritualMeaning: 'Khai sáng qua sự chân tự.',
    advice: 'Dừng lại, nhìn từ góc độ mới.',
    positiveMeaning: 'Sự chân tự, thay đổi quan điểm, khôn ngoan.',
    negativeMeaning: 'Sự chân tự lâu dài, bế tắc, đau khổ.',
    reversedMeaning: 'Thoát khỏi sự chân tự, tiếp tục.',
    warning: 'Không phải mọi tạm dừng đều xấu.',
    element: 'Water',
    planet: 'Neptune',
    zodiac: 'Pisces',
    difficulty: 3,
    memoryLevel: 'hard',
  },
  {
    id: 13,
    name: 'Death',
    number: 13,
    arcana: 'Major',
    suit: null,
    imageEmoji: '💀',
    keywords: ['transformation', 'endings', 'beginnings', 'change', 'transition'],
    generalMeaning: 'Sự chuyển biến, kết thúc, bắt đầu mới.',
    loveMeaning: 'Kết thúc tình yêu, sự chuyển biến quan hệ.',
    careerMeaning: 'Kết thúc công việc, sự chuyển biến sự nghiệp.',
    familyMeaning: 'Sự chuyển biến gia đình, kết thúc giai đoạn.',
    healthMeaning: 'Sự chuyển biến sức khỏe, kết thúc bệnh.',
    futureMeaning: 'Sự chuyển biến lớn, kết thúc và khởi đầu.',
    spiritualMeaning: 'Sự chuyển biến tâm linh, tái sinh.',
    advice: 'Chấp nhận sự thay đổi, kết thúc mang lại khởi đầu.',
    positiveMeaning: 'Sự chuyển biến, khởi đầu mới, tái sinh.',
    negativeMeaning: 'Sự mất mát, đau khổ, khó khăn.',
    reversedMeaning: 'Chống lại sự thay đổi, vẫn bị kẹt.',
    warning: 'Sự chuyển biến là tự nhiên.',
    element: 'Water',
    planet: 'Scorpio',
    zodiac: 'Scorpio',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 14,
    name: 'Temperance',
    number: 14,
    arcana: 'Major',
    suit: null,
    imageEmoji: '⚗️',
    keywords: ['balance', 'moderation', 'patience', 'meaning', 'purpose'],
    generalMeaning: 'Sự cân bằng, vừa phải, kiên nhẫn.',
    loveMeaning: 'Cân bằng tình yêu, tình yêu vừa phải.',
    careerMeaning: 'Cân bằng công việc, mục đích sự nghiệp.',
    familyMeaning: 'Cân bằng gia đình, hài hòa.',
    healthMeaning: 'Cân bằng sức khỏe, vừa phải tập luyện.',
    futureMeaning: 'Cân bằng, hài hòa, mục đích rõ.',
    spiritualMeaning: 'Cân bằng tâm linh, khai sáng qua vừa phải.',
    advice: 'Tìm cân bằng, không cực đoan.',
    positiveMeaning: 'Cân bằng, vừa phải, hài hòa, kiên nhẫn.',
    negativeMeaning: 'Mất cân bằng, cực đoan.',
    reversedMeaning: 'Mất cân bằng, xung đột, cực đoan.',
    warning: 'Cân bằng không phải vô hành động.',
    element: 'Fire',
    planet: 'Sagittarius',
    zodiac: 'Sagittarius',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 15,
    name: 'The Devil',
    number: 15,
    arcana: 'Major',
    suit: null,
    imageEmoji: '😈',
    keywords: ['bondage', 'materialism', 'playfulness', 'detachment', 'freedom'],
    generalMeaning: 'Sự ràng buộc, vật chất, cám dỗ, tự do bị mất.',
    loveMeaning: 'Tình yêu cám dỗ, ràng buộc tình cảm.',
    careerMeaning: 'Ràng buộc công việc, cám dỗ vật chất.',
    familyMeaning: 'Ràng buộc gia đình, cám dỗ.',
    healthMeaning: 'Sự nghiện ngập, ràng buộc sức khỏe.',
    futureMeaning: 'Sự ràng buộc, cám dỗ, tách khỏi.',
    spiritualMeaning: 'Sự ràng buộc tinh thần, vật chất hóa.',
    advice: 'Nhận ra ràng buộc, tìm thoát khỏi.',
    positiveMeaning: 'Playfulness, sự thôi thúc, vật chất.',
    negativeMeaning: 'Ràng buộc, cám dỗ, lệ thuộc.',
    reversedMeaning: 'Thoát khỏi ràng buộc, giải phóng.',
    warning: 'Nhận ra ràng buộc trước khi quá muộn.',
    element: 'Earth',
    planet: 'Capricorn',
    zodiac: 'Capricorn',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 16,
    name: 'The Tower',
    number: 16,
    arcana: 'Major',
    suit: null,
    imageEmoji: '🌩️',
    keywords: ['sudden change', 'revelation', 'breakdown', 'awakening', 'chaos'],
    generalMeaning: 'Sự sụp đổ, tiết lộ bất ngờ, xáo trộn.',
    loveMeaning: 'Sụp đổ tình yêu, tiết lộ bí mật.',
    careerMeaning: 'Sụp đổ công việc, tiết lộ bất công.',
    familyMeaning: 'Sụp đổ gia đình, tiết lộ bí mật.',
    healthMeaning: 'Khủng hoảng sức khỏe, bệnh bất ngờ.',
    futureMeaning: 'Sụp đổ, tiết lộ, xáo trộn lớn.',
    spiritualMeaning: 'Khai sáng đau đớn, phá vỡ ảo tưởng.',
    advice: 'Sự phá vỡ mang lại sự thật.',
    positiveMeaning: 'Phá vỡ ảo tưởng, tiết lộ sự thật.',
    negativeMeaning: 'Sụp đổ, tổn hại, hỗn loạn.',
    reversedMeaning: 'Tránh phá vỡ, phục hồi, tái xây dựng.',
    warning: 'Sự phá vỡ mang lại giải phóng.',
    element: 'Fire',
    planet: 'Mars',
    zodiac: 'Aries',
    difficulty: 3,
    memoryLevel: 'hard',
  },
  {
    id: 17,
    name: 'The Star',
    number: 17,
    arcana: 'Major',
    suit: null,
    imageEmoji: '⭐',
    keywords: ['hope', 'faith', 'renewal', 'spirituality', 'healing'],
    generalMeaning: 'Hy vọng, niềm tin, chữa lành, kỳ vọng.',
    loveMeaning: 'Hy vọng tình yêu, niềm tin tình cảm.',
    careerMeaning: 'Hy vọng công việc, niềm tin sự nghiệp.',
    familyMeaning: 'Hy vọng gia đình, niềm tin gia đình.',
    healthMeaning: 'Hy vọng chữa lành, niềm tin sức khỏe.',
    futureMeaning: 'Hy vọng, niềm tin, chữa lành.',
    spiritualMeaning: 'Tâm linh, hy vọng tâm linh, khai sáng cao.',
    advice: 'Giữ niềm tin, ánh sáng luôn tồn tại.',
    positiveMeaning: 'Hy vọng, niềm tin, chữa lành, ước mơ.',
    negativeMeaning: 'Mất hy vọng, bệnh tâm lý, tuyệt vọng.',
    reversedMeaning: 'Mất hy vọng, mất niềm tin.',
    warning: 'Hy vọng là lực mạnh.',
    element: 'Air',
    planet: 'Aquarius',
    zodiac: 'Aquarius',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 18,
    name: 'The Moon',
    number: 18,
    arcana: 'Major',
    suit: null,
    imageEmoji: '🌙',
    keywords: ['illusion', 'fear', 'anxiety', 'subconscious', 'intuition'],
    generalMeaning: 'Ảo tưởng, sợ hãi, lo lắng, bất ổn định.',
    loveMeaning: 'Bất ổn định tình yêu, sợ hãi tình cảm.',
    careerMeaning: 'Bất ổn định công việc, sợ hãi sự nghiệp.',
    familyMeaning: 'Bất ổn định gia đình, sợ hãi.',
    healthMeaning: 'Lo lắng sức khỏe, sợ hãi bệnh tật.',
    futureMeaning: 'Lo lắng, bất ổn định, khám phá bên trong.',
    spiritualMeaning: 'Sợ hãi tâm linh, ảo tưởng tâm linh.',
    advice: 'Đối mặt với sợ hãi, trực giác dẫn qua.',
    positiveMeaning: 'Trực giác, tâm linh, kỹ năng tâm lý.',
    negativeMeaning: 'Sợ hãi, lo lắng, ảo tưởng, bệnh tâm lý.',
    reversedMeaning: 'Vượt qua sợ hãi, sự rõ ràng.',
    warning: 'Phân biệt trực giác thật và sợ hãi.',
    element: 'Water',
    planet: 'Pisces',
    zodiac: 'Pisces',
    difficulty: 3,
    memoryLevel: 'hard',
  },
  {
    id: 19,
    name: 'The Sun',
    number: 19,
    arcana: 'Major',
    suit: null,
    imageEmoji: '☀️',
    keywords: ['positivity', 'fun', 'warmth', 'success', 'vitality'],
    generalMeaning: 'Thành công, vui vẻ, ánh nắng, hạnh phúc.',
    loveMeaning: 'Tình yêu thành công, hạnh phúc tình cảm.',
    careerMeaning: 'Thành công công việc, hạnh phúc sự nghiệp.',
    familyMeaning: 'Hạnh phúc gia đình, vui vẻ gia đình.',
    healthMeaning: 'Sức khỏe tốt, vui vẻ, năng lượng cao.',
    futureMeaning: 'Thành công, hạnh phúc, ánh sáng.',
    spiritualMeaning: 'Tâm linh sáng, khai sáng cao.',
    advice: 'Tận hưởng ánh sáng, hạnh phúc là quyền.',
    positiveMeaning: 'Thành công, hạnh phúc, ánh sáng, vui vẻ.',
    negativeMeaning: 'Thất bại, buồn bã, tối tăm.',
    reversedMeaning: 'Mất thành công, buồn bã.',
    warning: 'Tiếp tục tỏa sáng để duy trì ánh sáng.',
    element: 'Fire',
    planet: 'Sun',
    zodiac: 'Leo',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 20,
    name: 'Judgement',
    number: 20,
    arcana: 'Major',
    suit: null,
    imageEmoji: '📯',
    keywords: ['rebirth', 'calling', 'absolution', 'reckoning', 'awakening'],
    generalMeaning: 'Tái sinh, tiếng gọi nội tâm, tha thứ, sự thức tỉnh.',
    loveMeaning: 'Tái sinh tình yêu, tiếng gọi tình cảm.',
    careerMeaning: 'Tái sinh sự nghiệp, tiếng gọi chuyên môn.',
    familyMeaning: 'Tái sinh gia đình, tiếng gọi gia đình.',
    healthMeaning: 'Tái sinh sức khỏe, chữa lành toàn diện.',
    futureMeaning: 'Tái sinh, tiếng gọi, sự thức tỉnh.',
    spiritualMeaning: 'Khai sáng cao, tiếng gọi tâm linh.',
    advice: 'Nghe tiếng gọi nội tâm, tái sinh tự do.',
    positiveMeaning: 'Tái sinh, khai sáng, tiếng gọi, tha thứ.',
    negativeMeaning: 'Không lắng nghe, tự lừa dối.',
    reversedMeaning: 'Chưa sẵn sàng, từ chối tái sinh.',
    warning: 'Tiếng gọi này là một lần, hãy lắng nghe.',
    element: 'Fire',
    planet: 'Pluto',
    zodiac: 'Scorpio',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 21,
    name: 'The World',
    number: 21,
    arcana: 'Major',
    suit: null,
    imageEmoji: '🌍',
    keywords: ['completion', 'fulfillment', 'travel', 'closure', 'accomplishment'],
    generalMeaning: 'Hoàn thành, đạt được mục tiêu, du lịch, viên mãn.',
    loveMeaning: 'Hoàn thành tình yêu, hôn nhân, viên mãn.',
    careerMeaning: 'Hoàn thành dự án, thành công sự nghiệp.',
    familyMeaning: 'Viên mãn gia đình, du lịch gia đình.',
    healthMeaning: 'Hoàn thành chữa lành, sức khỏe viên mãn.',
    futureMeaning: 'Hoàn thành, viên mãn, thành công.',
    spiritualMeaning: 'Khai sáng toàn diện, viên mãn tâm linh.',
    advice: 'Bạn đã hoàn thành, chuẩn bị chu kỳ mới.',
    positiveMeaning: 'Hoàn thành, viên mãn, thành công.',
    negativeMeaning: 'Chưa hoàn thành, bế tắc.',
    reversedMeaning: 'Chưa sẵn sàng kết thúc, còn gì cần.',
    warning: 'Kết thúc là khởi đầu.',
    element: 'Earth',
    planet: 'Saturn',
    zodiac: 'All',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  // MINOR ARCANA - CUPS (22-35)
  {
    id: 22,
    name: 'Ace of Cups',
    number: 1,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '🏆',
    keywords: ['new feelings', 'relationships', 'compassion', 'forgiveness', 'awakening'],
    generalMeaning: 'Tình yêu mới, cảm xúc mới, tha thứ.',
    loveMeaning: 'Tình yêu mới bắt đầu, cảm xúc sâu sắc.',
    careerMeaning: 'Sự hợp tác mới, tình bạn công việc.',
    familyMeaning: 'Tình yêu gia đình mới, sự mở lòng.',
    healthMeaning: 'Chữa lành tâm lý, cảm xúc tích cực.',
    futureMeaning: 'Cảm xúc mới, tình yêu, kỳ vọng.',
    spiritualMeaning: 'Kỳ vọng tâm linh, tình yêu vũ trụ.',
    advice: 'Mở lòng cho cảm xúc mới.',
    positiveMeaning: 'Tình yêu, cảm xúc, sự mở lòng.',
    negativeMeaning: 'Mất cảm xúc, cấm đoán tình cảm.',
    reversedMeaning: 'Mất tình yêu, cảm xúc bị chặn.',
    warning: 'Tin tưởng cảm xúc của bạn.',
    element: 'Water',
    planet: 'Venus',
    zodiac: 'Cancer',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 23,
    name: 'Two of Cups',
    number: 2,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '💕',
    keywords: ['partnership', 'mutual respect', 'trust', 'harmony', 'agreement'],
    generalMeaning: 'Hợp tác, tôn trọng lẫn nhau, tin tưởng, hài hòa.',
    loveMeaning: 'Tình yêu đôi lứa, cam kết, hôn nhân.',
    careerMeaning: 'Hợp tác công việc, tin tưởng đối tác.',
    familyMeaning: 'Liên kết gia đình, tôn trọng lẫn nhau.',
    healthMeaning: 'Cân bằng tinh thần, hài hòa cơ thể.',
    futureMeaning: 'Hợp tác sẽ thành công, tin tưởng.',
    spiritualMeaning: 'Kết nối linh hồn, hài hòa tinh thần.',
    advice: 'Tin tưởng vào hợp tác, tôn trọng nhau.',
    positiveMeaning: 'Hợp tác, tin tưởng, hài hòa, cam kết.',
    negativeMeaning: 'Mất tin tưởng, chia rẽ, xung đột.',
    reversedMeaning: 'Hợp tác sụp đổ, mất tin tưởng.',
    warning: 'Duy trì tin tưởng trong hợp tác.',
    element: 'Water',
    planet: 'Venus',
    zodiac: 'Cancer',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 24,
    name: 'Three of Cups',
    number: 3,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '🎉',
    keywords: ['celebration', 'gathering', 'friendship', 'community', 'joy'],
    generalMeaning: 'Lễ kỷ niệm, tập hợp, tình bạn, hòa vui.',
    loveMeaning: 'Lễ kỷ niệm tình yêu, vui vẻ cặp đôi.',
    careerMeaning: 'Đồng tình công việc, tập hợp thành công.',
    familyMeaning: 'Tập hợp gia đình, vui vẻ chung.',
    healthMeaning: 'Vui vẻ sức khỏe, hòa lạc xã hội.',
    futureMeaning: 'Sẽ có lễ kỷ niệm, vui vẻ.',
    spiritualMeaning: 'Cộng đồng tâm linh, hòa vui chung.',
    advice: 'Chia sẻ vui vẻ với những người xung quanh.',
    positiveMeaning: 'Tập hợp, tình bạn, vui vẻ, lễ kỷ niệm.',
    negativeMeaning: 'Cô lập, buồn bã, tách rời.',
    reversedMeaning: 'Hỷ sự bị hoãn, tách rời.',
    warning: 'Chia sẻ vui vẻ, không giữ kín.',
    element: 'Water',
    planet: 'Mercury',
    zodiac: 'Cancer',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 25,
    name: 'Four of Cups',
    number: 4,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '💭',
    keywords: ['apathy', 'contemplation', 'reevaluation', 'missed opportunity'],
    generalMeaning: 'Sự thờ ơ, suy ngẫm, đánh giá lại, bỏ lỡ cơ hội.',
    loveMeaning: 'Sự thờ ơ tình yêu, chưa sẵn sàng.',
    careerMeaning: 'Suy ngẫm công việc, bỏ lỡ cơ hội.',
    familyMeaning: 'Suy ngẫm gia đình, cần thay đổi.',
    healthMeaning: 'Sự thờ ơ sức khỏe, cần chú ý.',
    futureMeaning: 'Cần suy ngẫm, bỏ lỡ có thể xảy ra.',
    spiritualMeaning: 'Suy ngẫm tâm linh, cần mở lòng.',
    advice: 'Không bỏ lỡ cơ hội, thức tỉnh.',
    positiveMeaning: 'Suy ngẫm, tạm dừng, đánh giá.',
    negativeMeaning: 'Sự thờ ơ, bỏ lỡ, từ chối.',
    reversedMeaning: 'Kết thúc sự thờ ơ, chấp nhận cơ hội.',
    warning: 'Đừng bỏ lỡ những cơ hội tốt.',
    element: 'Water',
    planet: 'Moon',
    zodiac: 'Cancer',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 26,
    name: 'Five of Cups',
    number: 5,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '😢',
    keywords: ['disappointment', 'loss', 'grief', 'sorrow', 'regret'],
    generalMeaning: 'Sự thất vọng, mất mát, buồn bã, hối tiếc.',
    loveMeaning: 'Chia tay, tình yêu mất, buồn bã tình cảm.',
    careerMeaning: 'Thất bại công việc, mất cơ hội.',
    familyMeaning: 'Mất thành viên gia đình, buồn bã.',
    healthMeaning: 'Buồn bã, sức khỏe tâm lý yếu.',
    futureMeaning: 'Sẽ có thử thách, nhưng sẽ vượt qua.',
    spiritualMeaning: 'Suy tư tinh thần, cần chữa lành.',
    advice: 'Cho phép bản thân buồn bã, sẽ hết.',
    positiveMeaning: 'Sự thật được tiết lộ, chữa lành bắt đầu.',
    negativeMeaning: 'Sụp đổ hoàn toàn, mất hy vọng.',
    reversedMeaning: 'Bắt đầu phục hồi, hy vọng trở lại.',
    warning: 'Buồn bã là bình thường, chữa lành sẽ đến.',
    element: 'Water',
    planet: 'Mars',
    zodiac: 'Scorpio',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 27,
    name: 'Six of Cups',
    number: 6,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '🎁',
    keywords: ['nostalgia', 'innocence', 'childhood', 'simplicity', 'generosity'],
    generalMeaning: 'Hoài niệm, ngây thơ, tuổi thơ, sự giản dị.',
    loveMeaning: 'Tình yêu tuổi trẻ, tình cảm thuần khiết.',
    careerMeaning: 'Công việc đơn giản, sự tùy thuận.',
    familyMeaning: 'Hoài niệm gia đình, tình thương gia đình.',
    healthMeaning: 'Sức khỏe ngây thơ, tình yêu bản thân.',
    futureMeaning: 'Sẽ trở về với đơn giản, tình yêu.',
    spiritualMeaning: 'Trở về nguồn gốc tâm linh, ngây thơ.',
    advice: 'Nhớ lại sự ngây thơ, đơn giản hóa.',
    positiveMeaning: 'Hoài niệm tốt, sự giản dị, tình thương.',
    negativeMeaning: 'Quá hoài niệm, sống trong quá khứ.',
    reversedMeaning: 'Bỏ qua tuổi thơ, trưởng thành.',
    warning: 'Cân bằng hoài niệm với hiện tại.',
    element: 'Water',
    planet: 'Sun',
    zodiac: 'Libra',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 28,
    name: 'Seven of Cups',
    number: 7,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '✨',
    keywords: ['illusion', 'fantasy', 'choices', 'wishful thinking', 'uncertainty'],
    generalMeaning: 'Ảo tưởng, mộng mơ, lựa chọn, suy nghĩ thoái thác.',
    loveMeaning: 'Tình yêu ảo tưởng, lựa chọn khó khăn.',
    careerMeaning: 'Cơ hội ảo tưởng, lựa chọn công việc.',
    familyMeaning: 'Ảo tưởng gia đình, lựa chọn khó.',
    healthMeaning: 'Ảo tưởng sức khỏe, cần xác thực.',
    futureMeaning: 'Sẽ có lựa chọn, cần sáng suốt.',
    spiritualMeaning: 'Ảo tưởng tâm linh, cần thực tế.',
    advice: 'Phân biệt ảo tưởng và hiện thực.',
    positiveMeaning: 'Mộng mơ sáng tạo, tưởng tượng.',
    negativeMeaning: 'Ảo tưởng hoàn toàn, bỏ lỡ.',
    reversedMeaning: 'Thực tế bộc lộ, sáng suốt.',
    warning: 'Không bị mộng mơ lôi cuốn, sống thực tế.',
    element: 'Water',
    planet: 'Venus',
    zodiac: 'Scorpio',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 29,
    name: 'Eight of Cups',
    number: 8,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '🚶',
    keywords: ['leaving', 'letting go', 'searching', 'moving on', 'abandonment'],
    generalMeaning: 'Rời bỏ, buông tay, tìm kiếm, tiếp tục.',
    loveMeaning: 'Rời bỏ tình yêu, buông tay tình cảm.',
    careerMeaning: 'Rời bỏ công việc, tìm sự nghiệp mới.',
    familyMeaning: 'Rời bỏ gia đình, tìm con đường riêng.',
    healthMeaning: 'Rời bỏ thói quen xấu, chữa lành.',
    futureMeaning: 'Sẽ rời bỏ, tìm kiếm điều mới.',
    spiritualMeaning: 'Rời bỏ ảo tưởng, tìm lẽ thật.',
    advice: 'Rời bỏ khi cần thiết, tìm con đường.',
    positiveMeaning: 'Rời bỏ xấu, tìm tốt hơn.',
    negativeMeaning: 'Rời bỏ quá vội, bỏ lỡ cơ hội.',
    reversedMeaning: 'Quay lại, tiếp tục, không rời bỏ.',
    warning: 'Rời bỏ không phải tẩu thoát.',
    element: 'Water',
    planet: 'Saturn',
    zodiac: 'Pisces',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 30,
    name: 'Nine of Cups',
    number: 9,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '😊',
    keywords: ['satisfaction', 'gratitude', 'abundance', 'wish', 'fulfillment'],
    generalMeaning: 'Sự hài lòng, biết ơn, phong phú, ước mơ thành công.',
    loveMeaning: 'Hài lòng tình yêu, ước mơ tình cảm thành hiện thực.',
    careerMeaning: 'Hài lòng công việc, thành công sự nghiệp.',
    familyMeaning: 'Hài lòng gia đình, biết ơn gia đình.',
    healthMeaning: 'Hài lòng sức khỏe, sức khỏe tốt.',
    futureMeaning: 'Ước mơ sẽ thành hiện thực, hạnh phúc.',
    spiritualMeaning: 'Hài lòng tâm linh, phong phú tinh thần.',
    advice: 'Biết ơn những gì có, ước mơ sẽ thành.',
    positiveMeaning: 'Hài lòng, phong phú, ước mơ, đạt được.',
    negativeMeaning: 'Bất mãn, nài nỉ, tham lam.',
    reversedMeaning: 'Mất hài lòng, bất mãn, cần chú ý.',
    warning: 'Biết ơn những gì đã có.',
    element: 'Water',
    planet: 'Jupiter',
    zodiac: 'Pisces',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 31,
    name: 'Ten of Cups',
    number: 10,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '👨‍👩‍👧‍👦',
    keywords: ['harmony', 'happiness', 'family', 'contentment', 'legacy'],
    generalMeaning: 'Hòa hợp, hạnh phúc, gia đình, viên mãn.',
    loveMeaning: 'Hạnh phúc gia đình hôn nhân, tình yêu hoàn hảo.',
    careerMeaning: 'Hài lòng công việc, hài hòa nhóm.',
    familyMeaning: 'Hạnh phúc gia đình toàn diện, hòa hợp.',
    healthMeaning: 'Sức khỏe gia đình, hạnh phúc thể chất.',
    futureMeaning: 'Gia đình hạnh phúc, hài hòa.',
    spiritualMeaning: 'Viên mãn tâm linh, hòa hợp toàn diện.',
    advice: 'Xây dựng gia đình hạnh phúc, hòa hợp.',
    positiveMeaning: 'Gia đình, hạnh phúc, hài hòa, viên mãn.',
    negativeMeaning: 'Gia đình tan vỡ, mất hạnh phúc.',
    reversedMeaning: 'Gia đình có vấn đề, cần giải quyết.',
    warning: 'Duy trì hòa hợp gia đình.',
    element: 'Water',
    planet: 'Sun',
    zodiac: 'Pisces',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 32,
    name: 'Page of Cups',
    number: 11,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '👦',
    keywords: ['curiosity', 'imagination', 'sensitivity', 'potential', 'innocence'],
    generalMeaning: 'Tò mò, tưởng tượng, nhạy cảm, tiềm năng.',
    loveMeaning: 'Tình yêu tuổi trẻ, cảm xúc nhạy cảm.',
    careerMeaning: 'Học tập mới, tiềm năng công việc.',
    familyMeaning: 'Con cái, tiềm năng gia đình.',
    healthMeaning: 'Sức khỏe tuổi trẻ, nhạy cảm cảm xúc.',
    futureMeaning: 'Tiềm năng sẽ phát triển, học tập.',
    spiritualMeaning: 'Tiềm năng tâm linh, tưởng tượng sáng.',
    advice: 'Phát triển tiềm năng, sáng tạo.',
    positiveMeaning: 'Tò mò, tưởng tượng, tiềm năng, học.',
    negativeMeaning: 'Thiếu kỹ năng, quá tuổi trẻ, bồng bột.',
    reversedMeaning: 'Mất tiềm năng, không muốn học.',
    warning: 'Phát triển tiềm năng khi còn trẻ.',
    element: 'Water',
    planet: 'Mercury',
    zodiac: 'Pisces',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 33,
    name: 'Knight of Cups',
    number: 12,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '🎭',
    keywords: ['romance', 'charm', 'creativity', 'idealism', 'moodiness'],
    generalMeaning: 'Lãng mạn, quyến rũ, sáng tạo, lý tưởng.',
    loveMeaning: 'Người yêu lãng mạn, sự quyến rũ, tình yêu lý tưởng.',
    careerMeaning: 'Sáng tạo, quyến rũ khách hàng, lý tưởng.',
    familyMeaning: 'Người trẻ sáng tạo, lý tưởng gia đình.',
    healthMeaning: 'Sức khỏe cảm xúc, sáng tạo y tế.',
    futureMeaning: 'Sẽ có lãng mạn, sáng tạo, lý tưởng.',
    spiritualMeaning: 'Sáng tạo tâm linh, lý tưởng tâm linh.',
    advice: 'Cân bằng lý tưởng với hiện thực.',
    positiveMeaning: 'Lãng mạn, sáng tạo, quyến rũ, lý tưởng.',
    negativeMeaning: 'Lý tưởng quá, bồng bột, hay thay đổi.',
    reversedMeaning: 'Mất sáng tạo, bệnh tâm lý, không lý tưởng.',
    warning: 'Không quá lý tưởng, thực tế là cần.',
    element: 'Water',
    planet: 'Venus',
    zodiac: 'Cancer',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 34,
    name: 'Queen of Cups',
    number: 13,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '👑',
    keywords: ['compassion', 'calm', 'nurturing', 'intuitive', 'emotionally intelligent'],
    generalMeaning: 'Lòng trắc ẩn, bình tĩnh, chăm sóc, trực giác.',
    loveMeaning: 'Người phụ nữ chăm sóc, tình yêu trắc ẩn.',
    careerMeaning: 'Lãnh đạo nữ, chăm sóc nhân viên.',
    familyMeaning: 'Người mẹ chăm sóc, trực giác gia đình.',
    healthMeaning: 'Sức khỏe cảm xúc, chữa lành.',
    futureMeaning: 'Sẽ có sự chăm sóc, bình tĩnh, trực giác.',
    spiritualMeaning: 'Trực giác tâm linh cao, chăm sóc.',
    advice: 'Lắng nghe trực giác, chăm sóc bản thân.',
    positiveMeaning: 'Trắc ẩn, bình tĩnh, chăm sóc, trực giác.',
    negativeMeaning: 'Cảm xúc quá, mất bình tĩnh.',
    reversedMeaning: 'Mất trắc ẩn, khô cứng cảm xúc.',
    warning: 'Chăm sóc bản thân cũng như người khác.',
    element: 'Water',
    planet: 'Water',
    zodiac: 'Cancer',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 35,
    name: 'King of Cups',
    number: 14,
    arcana: 'Minor',
    suit: 'Cups',
    imageEmoji: '👑',
    keywords: ['emotional balance', 'diplomacy', 'wisdom', 'maturity', 'control'],
    generalMeaning: 'Cân bằng cảm xúc, ngoại giao, khôn ngoan.',
    loveMeaning: 'Người đàn ông chín chắn, cân bằng cảm xúc.',
    careerMeaning: 'Lãnh đạo khôn ngoan, ngoại giao công việc.',
    familyMeaning: 'Người cha chín chắn, cân bằng gia đình.',
    healthMeaning: 'Cân bằng sức khỏe, kiểm soát cảm xúc.',
    futureMeaning: 'Sẽ có cân bằng, khôn ngoan, kiểm soát.',
    spiritualMeaning: 'Khôn ngoan tâm linh, cân bằng toàn diện.',
    advice: 'Cân bằng cảm xúc, khôn ngoan trong quyết định.',
    positiveMeaning: 'Cân bằng, khôn ngoan, ngoại giao, điềm.',
    negativeMeaning: 'Cảm xúc bị kìm nén, khó giao tiếp.',
    reversedMeaning: 'Mất cân bằng, cảm xúc nổ ra.',
    warning: 'Cân bằng cảm xúc là khôn ngoan.',
    element: 'Water',
    planet: 'Water',
    zodiac: 'Cancer',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  // MINOR ARCANA - WANDS (36-49)
  {
    id: 36,
    name: 'Ace of Wands',
    number: 1,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '🔥',
    keywords: ['new opportunities', 'growth', 'potential', 'energy', 'passion'],
    generalMeaning: 'Cơ hội mới, tăng trưởng, tiềm năng, năng lượng.',
    loveMeaning: 'Passion mới, năng lượng tình yêu, tình cảm sôi nổi.',
    careerMeaning: 'Dự án mới, cơ hội sự nghiệp, năng lượng công việc.',
    familyMeaning: 'Năng lượng gia đình, tăng trưởng gia đình.',
    healthMeaning: 'Năng lượng sức khỏe, sức mạnh.',
    futureMeaning: 'Cơ hội mới sẽ đến, năng lượng tăng.',
    spiritualMeaning: 'Năng lượng tâm linh, khai sáng mới.',
    advice: 'Tận dụng cơ hội mới, khơi dậy passion.',
    positiveMeaning: 'Cơ hội, năng lượng, passion, tăng trưởng.',
    negativeMeaning: 'Cơ hội bị lỡ, thiếu năng lượng.',
    reversedMeaning: 'Năng lượng thấp, cơ hội chưa tới.',
    warning: 'Tận dụng năng lượng này khi nó đến.',
    element: 'Fire',
    planet: 'Mars',
    zodiac: 'Aries',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 37,
    name: 'Two of Wands',
    number: 2,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '🌍',
    keywords: ['planning', 'making decisions', 'leaving home', 'exploration'],
    generalMeaning: 'Lập kế hoạch, quyết định, rời khỏi nhà, khám phá.',
    loveMeaning: 'Quyết định tình yêu, lập kế hoạch tương lai.',
    careerMeaning: 'Lập kế hoạch công việc, quyết định sự nghiệp.',
    familyMeaning: 'Quyết định gia đình, khám phá bên ngoài.',
    healthMeaning: 'Lập kế hoạch sức khỏe, khám phá.',
    futureMeaning: 'Sẽ có quyết định, khám phá cơ hội.',
    spiritualMeaning: 'Lập kế hoạch tâm linh, khám phá con đường.',
    advice: 'Lập kế hoạch cẩn thận, khám phá thế giới.',
    positiveMeaning: 'Lập kế hoạch, quyết định tốt, khám phá.',
    negativeMeaning: 'Thiếu kế hoạch, quyết định sai.',
    reversedMeaning: 'Chưa sẵn sàng quyết định, tiếp tục lên kế hoạch.',
    warning: 'Lập kế hoạch kỹ trước khi hành động.',
    element: 'Fire',
    planet: 'Venus',
    zodiac: 'Aries',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 38,
    name: 'Three of Wands',
    number: 3,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '✋',
    keywords: ['foresight', 'exploration', 'progress', 'confidence', 'expansion'],
    generalMeaning: 'Nhìn xa, khám phá, tiến bộ, tự tin, mở rộng.',
    loveMeaning: 'Tình yêu phát triển, tiến bộ quan hệ.',
    careerMeaning: 'Phát triển công việc, mở rộng sự nghiệp.',
    familyMeaning: 'Gia đình phát triển, mở rộng gia đình.',
    healthMeaning: 'Sức khỏe tiến bộ, phát triển sức mạnh.',
    futureMeaning: 'Sẽ có tiến bộ, mở rộng, khám phá.',
    spiritualMeaning: 'Phát triển tâm linh, mở rộng nhận thức.',
    advice: 'Nhìn xa, tiếp tục phát triển, mở rộng.',
    positiveMeaning: 'Tiến bộ, mở rộng, tự tin, khám phá.',
    negativeMeaning: 'Thiếu tiến bộ, không mở rộng.',
    reversedMeaning: 'Tiến bộ bị chặn, thiếu tự tin.',
    warning: 'Nhìn xa khi lập kế hoạch.',
    element: 'Fire',
    planet: 'Sun',
    zodiac: 'Aries',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 39,
    name: 'Four of Wands',
    number: 4,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '🏡',
    keywords: ['celebration', 'home', 'reunion', 'harmony', 'stability'],
    generalMeaning: 'Lễ kỷ niệm, nhà cửa, tái hợp, hòa hợp, ổn định.',
    loveMeaning: 'Lễ kỷ niệm tình yêu, tái hợp yêu đương.',
    careerMeaning: 'Lễ kỷ niệm công việc, ổn định sự nghiệp.',
    familyMeaning: 'Lễ kỷ niệm gia đình, tái hợp gia đình.',
    healthMeaning: 'Sức khỏe ổn định, lễ kỷ niệm chữa lành.',
    futureMeaning: 'Sẽ có lễ kỷ niệm, ổn định, hòa hợp.',
    spiritualMeaning: 'Lễ kỷ niệm tâm linh, ổn định con đường.',
    advice: 'Ổn định gốc rễ, tổ chức lễ kỷ niệm.',
    positiveMeaning: 'Lễ kỷ niệm, nhà cửa, ổn định, hòa hợp.',
    negativeMeaning: 'Mất ổn định, lễ kỷ niệm bị hỏng.',
    reversedMeaning: 'Mất hòa hợp, lễ kỷ niệm hoãn lại.',
    warning: 'Gắn bó với nhà cửa và gia đình.',
    element: 'Fire',
    planet: 'Venus',
    zodiac: 'Leo',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 40,
    name: 'Five of Wands',
    number: 5,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '⚔️',
    keywords: ['conflict', 'disagreement', 'competition', 'tension', 'clashing'],
    generalMeaning: 'Xung đột, không đồng ý, cạnh tranh, căng thẳng.',
    loveMeaning: 'Xung đột tình yêu, thường xuyên cãi nhau.',
    careerMeaning: 'Xung đột công việc, cạnh tranh sứ mệnh.',
    familyMeaning: 'Xung đột gia đình, cãi nhau gia đình.',
    healthMeaning: 'Căng thẳng sức khỏe, xung đột cảm xúc.',
    futureMeaning: 'Sẽ có xung đột, cạnh tranh, căng thẳng.',
    spiritualMeaning: 'Xung đột tâm linh, cạnh tranh tôn giáo.',
    advice: 'Giải quyết xung đột, hòa giải.',
    positiveMeaning: 'Cạnh tranh sáng khỏe, sự thách đấu.',
    negativeMeaning: 'Xung đột lâu dài, cãi nhau liên tục.',
    reversedMeaning: 'Xung đột giải quyết, hòa hợp trở lại.',
    warning: 'Giải quyết xung đột trước khi trở nên tồi tệ.',
    element: 'Fire',
    planet: 'Saturn',
    zodiac: 'Leo',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 41,
    name: 'Six of Wands',
    number: 6,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '🏆',
    keywords: ['victory', 'success', 'public recognition', 'confidence', 'achievement'],
    generalMeaning: 'Chiến thắng, thành công, công nhận công khai, tự tin.',
    loveMeaning: 'Chiến thắng tình yêu, công nhận quan hệ.',
    careerMeaning: 'Chiến thắng công việc, công nhận sự nghiệp.',
    familyMeaning: 'Chiến thắng gia đình, công nhận gia đình.',
    healthMeaning: 'Chiến thắng sức khỏe, tự tin.',
    futureMeaning: 'Sẽ có chiến thắng, công nhận, tự tin.',
    spiritualMeaning: 'Chiến thắng tâm linh, công nhận con đường.',
    advice: 'Tự tin nhận công nhận, tương lai sáng.',
    positiveMeaning: 'Chiến thắng, thành công, công nhận, tự tin.',
    negativeMeaning: 'Thiếu tự tin, mất công nhận.',
    reversedMeaning: 'Thất bại công nhận, thua cuộc.',
    warning: 'Hãy khiêm tốn với thành công của mình.',
    element: 'Fire',
    planet: 'Jupiter',
    zodiac: 'Leo',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 42,
    name: 'Seven of Wands',
    number: 7,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '🛡️',
    keywords: ['perseverance', 'protection', 'challenge', 'determination', 'resilience'],
    generalMeaning: 'Kiên trì, bảo vệ, thách thức, quyết tâm, khả năng chịu đựng.',
    loveMeaning: 'Kiên trì tình yêu, bảo vệ quan hệ, thách thức.',
    careerMeaning: 'Kiên trì công việc, bảo vệ sự nghiệp, thách thức.',
    familyMeaning: 'Kiên trì gia đình, bảo vệ gia đình.',
    healthMeaning: 'Kiên trì chữa lành, bảo vệ sức khỏe.',
    futureMeaning: 'Sẽ có thách thức, kiên trì, bảo vệ.',
    spiritualMeaning: 'Kiên trì tâm linh, bảo vệ con đường.',
    advice: 'Kiên trì trong thách thức, bảo vệ bản thân.',
    positiveMeaning: 'Kiên trì, bảo vệ, quyết tâm, khả năng chịu.',
    negativeMeaning: 'Mệt mỏi kiên trì, bảo vệ không đủ.',
    reversedMeaning: 'Hạ vũ khí, chịu thua, bỏ cuộc.',
    warning: 'Kiên trì nhưng cũng cần biết khi nào nên dừng.',
    element: 'Fire',
    planet: 'Mars',
    zodiac: 'Sagittarius',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 43,
    name: 'Eight of Wands',
    number: 8,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '🚀',
    keywords: ['speed', 'action', 'acceleration', 'progress', 'clarity'],
    generalMeaning: 'Tốc độ, hành động, tăng tốc, tiến bộ, rõ ràng.',
    loveMeaning: 'Tốc độ tình yêu, hành động tình cảm nhanh.',
    careerMeaning: 'Tốc độ công việc, hành động sự nghiệp nhanh.',
    familyMeaning: 'Tốc độ gia đình, hành động gia đình.',
    healthMeaning: 'Tốc độ chữa lành, hành động sức khỏe.',
    futureMeaning: 'Sẽ có tốc độ, hành động nhanh, rõ ràng.',
    spiritualMeaning: 'Tốc độ tâm linh, rõ ràng con đường.',
    advice: 'Hành động nhanh, tận dụng thời gian.',
    positiveMeaning: 'Tốc độ, hành động, tiến bộ nhanh, rõ ràng.',
    negativeMeaning: 'Hành động quá nhanh, vội vàng, mất kiểm soát.',
    reversedMeaning: 'Chậm lại, thiếu tiến bộ, bế tắc.',
    warning: 'Hành động nhanh nhưng cẩn thận.',
    element: 'Fire',
    planet: 'Mercury',
    zodiac: 'Sagittarius',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 44,
    name: 'Nine of Wands',
    number: 9,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '💪',
    keywords: ['resilience', 'courage', 'strength', 'endurance', 'conviction'],
    generalMeaning: 'Khả năng chịu đựng, can đảm, sức mạnh, sự kiên trì.',
    loveMeaning: 'Can đảm tình yêu, sức mạnh quan hệ.',
    careerMeaning: 'Sức mạnh công việc, can đảm sự nghiệp.',
    familyMeaning: 'Sức mạnh gia đình, can đảm gia đình.',
    healthMeaning: 'Sức mạnh sức khỏe, khả năng chịu đựng.',
    futureMeaning: 'Sẽ có sức mạnh, can đảm, kiên trì.',
    spiritualMeaning: 'Sức mạnh tâm linh, can đảm con đường.',
    advice: 'Tin vào sức mạnh, kiên trì đến cuối cùng.',
    positiveMeaning: 'Can đảm, sức mạnh, kiên trì, quyết tâm.',
    negativeMeaning: 'Yếu đuối, mất can đảm, kiệt sức.',
    reversedMeaning: 'Mất sức mạnh, bỏ cuộc, mệt mỏi.',
    warning: 'Biết khi nào nên nghỉ ngơi, không phải cứ cố.',
    element: 'Fire',
    planet: 'Moon',
    zodiac: 'Sagittarius',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 45,
    name: 'Ten of Wands',
    number: 10,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '📦',
    keywords: ['burden', 'responsibilities', 'weight', 'stress', 'completion'],
    generalMeaning: 'Gánh nặng, trách nhiệm, áp lực, căng thẳng.',
    loveMeaning: 'Gánh nặng tình yêu, trách nhiệm quan hệ.',
    careerMeaning: 'Gánh nặng công việc, trách nhiệm quá tải.',
    familyMeaning: 'Gánh nặng gia đình, trách nhiệm gia đình.',
    healthMeaning: 'Stress sức khỏe, gánh nặng tâm lý.',
    futureMeaning: 'Sẽ có gánh nặng, trách nhiệm, căng thẳng.',
    spiritualMeaning: 'Gánh nặng tâm linh, trách nhiệm con đường.',
    advice: 'Từ bỏ gánh nặng không cần thiết.',
    positiveMeaning: 'Hoàn thành công việc, trách nhiệm cuối cùng.',
    negativeMeaning: 'Quá tải, căng thẳng liên tục, kiệt sức.',
    reversedMeaning: 'Bỏ đi gánh nặng, giảm tải.',
    warning: 'Đừng quá tải trách nhiệm, biết từ chối.',
    element: 'Fire',
    planet: 'Saturn',
    zodiac: 'Sagittarius',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 46,
    name: 'Page of Wands',
    number: 11,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '🎯',
    keywords: ['exploration', 'freedom', 'enthusiasm', 'adventure', 'discovery'],
    generalMeaning: 'Khám phá, tự do, hăng hái, phiêu lưu, khám phá.',
    loveMeaning: 'Tình yêu phiêu lưu, hăng hái tình cảm.',
    careerMeaning: 'Khám phá công việc, hăng hái sự nghiệp.',
    familyMeaning: 'Khám phá gia đình, tự do gia đình.',
    healthMeaning: 'Tự do sức khỏe, hăng hái chữa lành.',
    futureMeaning: 'Sẽ có khám phá, hăng hái, phiêu lưu.',
    spiritualMeaning: 'Khám phá tâm linh, hăng hái con đường.',
    advice: 'Khám phá, hãy tự do, sáng tạo.',
    positiveMeaning: 'Khám phá, hăng hái, tự do, phiêu lưu.',
    negativeMeaning: 'Bồng bột, không kiểm soát, vô trách nhiệm.',
    reversedMeaning: 'Mất hăng hái, thiếu sáng tạo, mất tự do.',
    warning: 'Khám phá là tốt nhưng cần có trách nhiệm.',
    element: 'Fire',
    planet: 'Mercury',
    zodiac: 'Aries',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 47,
    name: 'Knight of Wands',
    number: 12,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '🎪',
    keywords: ['passion', 'energy', 'adventure', 'impulsiveness', 'daring'],
    generalMeaning: 'Passion, năng lượng, phiêu lưu, bồng bột, dũng cảm.',
    loveMeaning: 'Passion tình yêu, phiêu lưu tình cảm.',
    careerMeaning: 'Passion công việc, dũng cảm sự nghiệp.',
    familyMeaning: 'Passion gia đình, dũng cảm gia đình.',
    healthMeaning: 'Passion sức khỏe, năng lượng cao.',
    futureMeaning: 'Sẽ có passion, năng lượng, phiêu lưu.',
    spiritualMeaning: 'Passion tâm linh, dũng cảm con đường.',
    advice: 'Kêu gọi passion nhưng cần kiểm soát.',
    positiveMeaning: 'Passion, năng lượng, dũng cảm, phiêu lưu.',
    negativeMeaning: 'Bồng bột, vô trách nhiệm, hành động vội vàng.',
    reversedMeaning: 'Mất passion, năng lượng thấp.',
    warning: 'Passion cần được hướng dẫn bởi khôn ngoan.',
    element: 'Fire',
    planet: 'Mars',
    zodiac: 'Aries',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 48,
    name: 'Queen of Wands',
    number: 13,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '👑',
    keywords: ['confidence', 'independence', 'determination', 'magnetism', 'courage'],
    generalMeaning: 'Tự tin, độc lập, quyết tâm, hấp dẫn, can đảm.',
    loveMeaning: 'Tự tin tình yêu, độc lập tình cảm.',
    careerMeaning: 'Tự tin công việc, độc lập sự nghiệp.',
    familyMeaning: 'Tự tin gia đình, độc lập gia đình.',
    healthMeaning: 'Tự tin sức khỏe, độc lập.',
    futureMeaning: 'Sẽ có tự tin, độc lập, can đảm.',
    spiritualMeaning: 'Tự tin tâm linh, can đảm con đường.',
    advice: 'Tự tin vào bản thân, độc lập sống.',
    positiveMeaning: 'Tự tin, độc lập, quyết tâm, can đảm.',
    negativeMeaning: 'Quá tự tin, kiêu ngạo, quá độc lập.',
    reversedMeaning: 'Mất tự tin, phụ thuộc, yếu đuối.',
    warning: 'Tự tin là tốt nhưng đừng quá tự tin.',
    element: 'Fire',
    planet: 'Venus',
    zodiac: 'Leo',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 49,
    name: 'King of Wands',
    number: 14,
    arcana: 'Minor',
    suit: 'Wands',
    imageEmoji: '👑',
    keywords: ['leadership', 'vision', 'entrepreneur', 'boldness', 'charisma'],
    generalMeaning: 'Lãnh đạo, tầm nhìn, doanh nhân, dũng cảm, quyến rũ.',
    loveMeaning: 'Lãnh đạo tình yêu, tầm nhìn tình cảm.',
    careerMeaning: 'Lãnh đạo công việc, doanh nhân sự nghiệp.',
    familyMeaning: 'Lãnh đạo gia đình, tầm nhìn gia đình.',
    healthMeaning: 'Lãnh đạo sức khỏe, dũng cảm chữa lành.',
    futureMeaning: 'Sẽ có lãnh đạo, tầm nhìn, dũng cảm.',
    spiritualMeaning: 'Lãnh đạo tâm linh, tầm nhìn con đường.',
    advice: 'Lãnh đạo với tầm nhìn rõ ràng.',
    positiveMeaning: 'Lãnh đạo, tầm nhìn, dũng cảm, quyến rũ.',
    negativeMeaning: 'Độc tài, vô ơn, kiêu ngạo.',
    reversedMeaning: 'Mất lãnh đạo, không có tầm nhìn.',
    warning: 'Lãnh đạo với trách nhiệm, không độc tài.',
    element: 'Fire',
    planet: 'Fire',
    zodiac: 'Leo',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  // MINOR ARCANA - SWORDS (50-63)
  {
    id: 50,
    name: 'Ace of Swords',
    number: 1,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '⚔️',
    keywords: ['clarity', 'truth', 'mental clarity', 'new ideas', 'breakthrough'],
    generalMeaning: 'Rõ ràng, sự thật, tư duy rõ, ý tưởng mới, đột phá.',
    loveMeaning: 'Rõ ràng tình yêu, sự thật tình cảm.',
    careerMeaning: 'Rõ ràng công việc, ý tưởng mới sự nghiệp.',
    familyMeaning: 'Rõ ràng gia đình, sự thật gia đình.',
    healthMeaning: 'Rõ ràng sức khỏe, chẩn đoán đúng.',
    futureMeaning: 'Sẽ có rõ ràng, sự thật, ý tưởng mới.',
    spiritualMeaning: 'Rõ ràng tâm linh, sự thật tinh thần.',
    advice: 'Tìm kiếm sự thật, suy nghĩ rõ ràng.',
    positiveMeaning: 'Rõ ràng, sự thật, ý tưởng mới, đột phá.',
    negativeMeaning: 'Nhầm lẫn, nói dối, ý tưởng sai.',
    reversedMeaning: 'Rối loạn tư duy, không rõ ràng.',
    warning: 'Tìm kiếm sự thật nhưng cẩn thận với lời nói.',
    element: 'Air',
    planet: 'Mercury',
    zodiac: 'Gemini',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 51,
    name: 'Two of Swords',
    number: 2,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '🙈',
    keywords: ['stalemate', 'difficult choices', 'blockage', 'indecision', 'confusion'],
    generalMeaning: 'Bế tắc, lựa chọn khó, bị chặn, không quyết định.',
    loveMeaning: 'Bế tắc tình yêu, không quyết định tình cảm.',
    careerMeaning: 'Bế tắc công việc, lựa chọn khó sự nghiệp.',
    familyMeaning: 'Bế tắc gia đình, lựa chọn khó.',
    healthMeaning: 'Bế tắc sức khỏe, không biết chọn điều trị.',
    futureMeaning: 'Sẽ có bế tắc, lựa chọn khó, không rõ.',
    spiritualMeaning: 'Bế tắc tâm linh, không biết chọn.',
    advice: 'Bỏ mắt nạ, nhìn rõ tình huống.',
    positiveMeaning: 'Tạm dừng, cân bằng, chờ đợi.',
    negativeMeaning: 'Bế tắc lâu dài, không quyết định.',
    reversedMeaning: 'Quyết định cuối cùng, rõ ràng thông tin.',
    warning: 'Đừng chần chừ quá lâu khi lựa chọn.',
    element: 'Air',
    planet: 'Moon',
    zodiac: 'Libra',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 52,
    name: 'Three of Swords',
    number: 3,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '💔',
    keywords: ['heartbreak', 'sorrow', 'painful truths', 'difficult times', 'separation'],
    generalMeaning: 'Đau lòng, buồn bã, sự thật đau đớn, thời khó khăn.',
    loveMeaning: 'Đau lòng tình yêu, chia tay đau đớn.',
    careerMeaning: 'Khó khăn công việc, chia tay sự nghiệp.',
    familyMeaning: 'Khó khăn gia đình, chia tay gia đình.',
    healthMeaning: 'Khó khăn sức khỏe, bệnh tật đau đớn.',
    futureMeaning: 'Sẽ có khó khăn, đau đớn, chia tay.',
    spiritualMeaning: 'Khó khăn tâm linh, sự thật đau đớn.',
    advice: 'Chấp nhận nỗi đau, sẽ hồi phục.',
    positiveMeaning: 'Sự thật được tiết lộ, chữa lành bắt đầu.',
    negativeMeaning: 'Nỗi đau lâu dài, không phục hồi.',
    reversedMeaning: 'Nỗi đau giảm, phục hồi bắt đầu.',
    warning: 'Nỗi đau sẽ qua đi, không vĩnh viễn.',
    element: 'Air',
    planet: 'Saturn',
    zodiac: 'Libra',
    difficulty: 3,
    memoryLevel: 'hard',
  },
  {
    id: 53,
    name: 'Four of Swords',
    number: 4,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '🛌',
    keywords: ['rest', 'pause', 'contemplation', 'recovery', 'stillness'],
    generalMeaning: 'Nghỉ ngơi, tạm dừng, suy ngẫm, phục hồi sau khó khăn.',
    loveMeaning: 'Nghỉ ngơi trong tình yêu, tạm dừng để suy ngẫm quan hệ.',
    careerMeaning: 'Nghỉ ngơi công việc, tạm dừng để phục hồi năng lượng.',
    familyMeaning: 'Nghỉ ngơi gia đình, tạm dừng xung đột để suy ngẫm.',
    healthMeaning: 'Cần nghỉ ngơi, phục hồi sức khỏe, chữa lành.',
    futureMeaning: 'Sẽ có thời gian nghỉ ngơi, phục hồi trước khi tiếp tục.',
    spiritualMeaning: 'Tĩnh lặng tâm linh, suy ngẫm sâu, phục hồi nội tâm.',
    advice: 'Cho phép bản thân nghỉ ngơi trước khi tiếp tục chiến đấu.',
    positiveMeaning: 'Nghỉ ngơi, phục hồi, suy ngẫm, tĩnh lặng.',
    negativeMeaning: 'Trì hoãn quá lâu, không hành động, cô lập.',
    reversedMeaning: 'Cưỡng lại nghỉ ngơi, kiệt sức, không chịu dừng.',
    warning: 'Nghỉ ngơi là cần thiết, không phải dấu hiệu yếu đuối.',
    element: 'Air',
    planet: 'Jupiter',
    zodiac: 'Libra',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 54,
    name: 'Five of Swords',
    number: 5,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '🗡️',
    keywords: ['defeat', 'loss', 'conflict', 'tension', 'win at all costs'],
    generalMeaning: 'Thất bại, mất mát, xung đột, chiến thắng bằng mọi giá.',
    loveMeaning: 'Xung đột tình yêu, chiến thắng vô nghĩa, mất mát tình cảm.',
    careerMeaning: 'Xung đột công việc, cạnh tranh không lành mạnh.',
    familyMeaning: 'Xung đột gia đình gay gắt, mất mát quan hệ.',
    healthMeaning: 'Căng thẳng do xung đột, cần giải tỏa.',
    futureMeaning: 'Sẽ có xung đột, cần cân nhắc cái giá phải trả.',
    spiritualMeaning: 'Xung đột nội tâm, đấu tranh giữa cái tôi.',
    advice: 'Cân nhắc cái giá của chiến thắng, đôi khi nên buông bỏ.',
    positiveMeaning: 'Học từ thất bại, nhận ra bài học.',
    negativeMeaning: 'Thắng nhưng mất tất cả, quan hệ tan vỡ.',
    reversedMeaning: 'Hòa giải, buông bỏ oán hận, tìm hòa bình.',
    warning: 'Không phải chiến thắng nào cũng đáng để theo đuổi.',
    element: 'Air',
    planet: 'Venus',
    zodiac: 'Aquarius',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 55,
    name: 'Six of Swords',
    number: 6,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '🚤',
    keywords: ['transition', 'moving on', 'travel', 'communication', 'leaving behind'],
    generalMeaning: 'Chuyển tiếp, tiến về phía trước, du hành, để lại quá khứ.',
    loveMeaning: 'Chuyển tiếp trong tình yêu, rời khỏi giai đoạn khó khăn.',
    careerMeaning: 'Chuyển đổi công việc, di chuyển đến cơ hội mới.',
    familyMeaning: 'Chuyển tiếp gia đình, di dời, thay đổi hoàn cảnh.',
    healthMeaning: 'Chuyển tiếp sang giai đoạn hồi phục tốt hơn.',
    futureMeaning: 'Sẽ có sự chuyển tiếp êm đềm, tiến về phía trước.',
    spiritualMeaning: 'Hành trình tâm linh, rời bỏ đau khổ để tìm bình yên.',
    advice: 'Tin tưởng vào hành trình, để lại gánh nặng phía sau.',
    positiveMeaning: 'Chuyển tiếp tốt, tiến bộ, rời khỏi khó khăn.',
    negativeMeaning: 'Không thể rời đi, mắc kẹt trong quá khứ.',
    reversedMeaning: 'Trì hoãn chuyển tiếp, quay lại vấn đề cũ.',
    warning: 'Đôi khi cần rời đi để tìm được bình yên.',
    element: 'Air',
    planet: 'Mercury',
    zodiac: 'Aquarius',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 56,
    name: 'Seven of Swords',
    number: 7,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '🥷',
    keywords: ['deception', 'trickery', 'betrayal', 'secrets', 'strategy'],
    generalMeaning: 'Lừa dối, mưu mẹo, phản bội, bí mật, chiến lược.',
    loveMeaning: 'Lừa dối trong tình yêu, bí mật giấu kín, không trung thực.',
    careerMeaning: 'Mưu mẹo công việc, cần cẩn thận với đồng nghiệp.',
    familyMeaning: 'Bí mật gia đình, thiếu trung thực.',
    healthMeaning: 'Che giấu triệu chứng, không thành thật về sức khỏe.',
    futureMeaning: 'Cần cẩn thận, có thể có lừa dối xảy ra.',
    spiritualMeaning: 'Tự lừa dối bản thân, cần nhìn nhận sự thật.',
    advice: 'Trung thực với bản thân và người khác.',
    positiveMeaning: 'Chiến lược khôn khéo, độc lập giải quyết vấn đề.',
    negativeMeaning: 'Lừa dối, phản bội, hành động sau lưng.',
    reversedMeaning: 'Sự thật được phơi bày, lương tâm cắn rứt.',
    warning: 'Sự lừa dối cuối cùng sẽ bị phát hiện.',
    element: 'Air',
    planet: 'Moon',
    zodiac: 'Aquarius',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 57,
    name: 'Eight of Swords',
    number: 8,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '🪢',
    keywords: ['restriction', 'powerlessness', 'confusion', 'self-imposed prison'],
    generalMeaning: 'Sự hạn chế, bất lực, bối rối, tự giam mình trong suy nghĩ.',
    loveMeaning: 'Cảm thấy bị mắc kẹt trong tình yêu, tự hạn chế bản thân.',
    careerMeaning: 'Cảm thấy bế tắc công việc, tự giới hạn khả năng.',
    familyMeaning: 'Cảm thấy bị ràng buộc bởi kỳ vọng gia đình.',
    healthMeaning: 'Lo lắng quá mức, tự tạo áp lực tâm lý.',
    futureMeaning: 'Cần nhận ra rằng sự hạn chế phần lớn do tự mình tạo ra.',
    spiritualMeaning: 'Tù ngục tâm trí, cần giải phóng bản thân khỏi sợ hãi.',
    advice: 'Nhận ra rằng bạn có nhiều lựa chọn hơn bạn nghĩ.',
    positiveMeaning: 'Nhận thức được vấn đề, bắt đầu tìm lối thoát.',
    negativeMeaning: 'Cảm giác bất lực hoàn toàn, tự trói buộc.',
    reversedMeaning: 'Giải phóng bản thân, thoát khỏi nỗi sợ.',
    warning: 'Những rào cản thường tồn tại trong tâm trí nhiều hơn thực tế.',
    element: 'Air',
    planet: 'Jupiter',
    zodiac: 'Gemini',
    difficulty: 3,
    memoryLevel: 'hard',
  },
  {
    id: 58,
    name: 'Nine of Swords',
    number: 9,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '😰',
    keywords: ['anxiety', 'anguish', 'worry', 'despair', 'nightmares'],
    generalMeaning: 'Lo âu, đau khổ, lo lắng, tuyệt vọng, ác mộng.',
    loveMeaning: 'Lo lắng về tình yêu, sợ hãi mất mát trong quan hệ.',
    careerMeaning: 'Lo âu về công việc, căng thẳng, mất ngủ vì áp lực.',
    familyMeaning: 'Lo lắng cho gia đình, đau khổ vì mâu thuẫn.',
    healthMeaning: 'Lo âu, mất ngủ, căng thẳng tâm lý cần được chăm sóc.',
    futureMeaning: 'Nỗi lo thường lớn hơn thực tế, cần bình tĩnh nhìn nhận.',
    spiritualMeaning: 'Khủng hoảng tinh thần, cần tìm sự bình an nội tâm.',
    advice: 'Đối diện với nỗi sợ thay vì để nó ám ảnh trong bóng tối.',
    positiveMeaning: 'Nhận thức vấn đề, bắt đầu tìm cách giải quyết.',
    negativeMeaning: 'Lo âu tột độ, tuyệt vọng, ảnh hưởng đến sức khỏe.',
    reversedMeaning: 'Bắt đầu vượt qua nỗi lo, tìm được hy vọng.',
    warning: 'Nếu nỗi lo kéo dài, hãy tìm kiếm hỗ trợ từ người đáng tin cậy.',
    element: 'Air',
    planet: 'Mars',
    zodiac: 'Gemini',
    difficulty: 3,
    memoryLevel: 'hard',
  },
  {
    id: 59,
    name: 'Ten of Swords',
    number: 10,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '🌅',
    keywords: ['endings', 'ruin', 'betrayal', 'loss', 'rock bottom'],
    generalMeaning: 'Kết thúc, sụp đổ, phản bội, mất mát, chạm đáy.',
    loveMeaning: 'Kết thúc đau đớn trong tình yêu, nhưng cũng là khởi đầu mới.',
    careerMeaning: 'Kết thúc một giai đoạn công việc, chạm đáy để bật lên.',
    familyMeaning: 'Kết thúc xung đột gia đình sau đau khổ tột cùng.',
    healthMeaning: 'Giai đoạn khó khăn nhất đã qua, hồi phục sắp bắt đầu.',
    futureMeaning: 'Điều tồi tệ nhất đã kết thúc, bình minh sắp đến.',
    spiritualMeaning: 'Cái chết tượng trưng, tái sinh sau khổ đau tột cùng.',
    advice: 'Đây là điểm thấp nhất, từ đây chỉ có thể đi lên.',
    positiveMeaning: 'Kết thúc để mở ra khởi đầu mới, giải thoát.',
    negativeMeaning: 'Phản bội đau đớn, mất mát toàn diện.',
    reversedMeaning: 'Hồi phục dần dần, học được bài học từ mất mát.',
    warning: 'Sau đêm tối nhất luôn là bình minh.',
    element: 'Air',
    planet: 'Sun',
    zodiac: 'Gemini',
    difficulty: 3,
    memoryLevel: 'hard',
  },
  {
    id: 60,
    name: 'Page of Swords',
    number: 11,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '🗨️',
    keywords: ['curiosity', 'intelligence', 'communication', 'analysis', 'vigilance'],
    generalMeaning: 'Tò mò, thông minh, giao tiếp, phân tích, cảnh giác.',
    loveMeaning: 'Giao tiếp thẳng thắn trong tình yêu, tò mò về đối phương.',
    careerMeaning: 'Học hỏi nhanh, giao tiếp tốt trong công việc mới.',
    familyMeaning: 'Thành viên trẻ thông minh, thích đặt câu hỏi.',
    healthMeaning: 'Cần theo dõi sát sao sức khỏe, tìm hiểu thông tin.',
    futureMeaning: 'Sẽ có thông tin mới, cần phân tích cẩn thận.',
    spiritualMeaning: 'Khát khao tri thức tâm linh, tìm kiếm sự thật.',
    advice: 'Đặt câu hỏi, tìm hiểu kỹ trước khi hành động.',
    positiveMeaning: 'Thông minh, tò mò, giao tiếp tốt, cảnh giác.',
    negativeMeaning: 'Nói nhiều nhưng thiếu suy nghĩ, đưa tin đồn.',
    reversedMeaning: 'Thiếu thận trọng trong lời nói, thông tin sai lệch.',
    warning: 'Suy nghĩ kỹ trước khi nói, lời nói có sức mạnh.',
    element: 'Air',
    planet: 'Mercury',
    zodiac: 'Gemini',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 61,
    name: 'Knight of Swords',
    number: 12,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '🐎',
    keywords: ['action', 'impulsiveness', 'defending beliefs', 'ambition', 'speed'],
    generalMeaning: 'Hành động, bồng bột, bảo vệ niềm tin, tham vọng, tốc độ.',
    loveMeaning: 'Theo đuổi tình yêu quyết liệt, hành động nhanh trong quan hệ.',
    careerMeaning: 'Hành động quyết đoán, theo đuổi mục tiêu công việc.',
    familyMeaning: 'Thành viên hành động nhanh, đôi khi bồng bột.',
    healthMeaning: 'Năng lượng cao, cần tránh hành động vội vàng gây hại.',
    futureMeaning: 'Sẽ có hành động nhanh chóng, quyết đoán.',
    spiritualMeaning: 'Chiến đấu vì lý tưởng, bảo vệ niềm tin tâm linh.',
    advice: 'Hành động quyết đoán nhưng đừng quên suy nghĩ trước.',
    positiveMeaning: 'Quyết đoán, dũng cảm, hành động nhanh, tham vọng.',
    negativeMeaning: 'Hấp tấp, thiếu kiên nhẫn, hành động thiếu suy nghĩ.',
    reversedMeaning: 'Hành động không kiểm soát, gây hậu quả xấu.',
    warning: 'Tốc độ cần đi cùng với sự thận trọng.',
    element: 'Air',
    planet: 'Mars',
    zodiac: 'Libra',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 62,
    name: 'Queen of Swords',
    number: 13,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '👑',
    keywords: ['clarity', 'independence', 'truth', 'perception', 'directness'],
    generalMeaning: 'Rõ ràng, độc lập, sự thật, nhận thức sắc bén, thẳng thắn.',
    loveMeaning: 'Người phụ nữ độc lập, thẳng thắn về cảm xúc thật.',
    careerMeaning: 'Lãnh đạo sắc bén, ra quyết định dựa trên sự thật.',
    familyMeaning: 'Người mẹ thẳng thắn, độc lập, dạy con sự thật.',
    healthMeaning: 'Nhìn nhận sức khỏe rõ ràng, không né tránh sự thật.',
    futureMeaning: 'Sẽ cần sự rõ ràng và thẳng thắn để tiến lên.',
    spiritualMeaning: 'Trí tuệ sắc bén, nhìn thấu bản chất sự việc.',
    advice: 'Nói sự thật, nhưng hãy làm điều đó với lòng trắc ẩn.',
    positiveMeaning: 'Rõ ràng, độc lập, công bằng, sắc sảo.',
    negativeMeaning: 'Lạnh lùng, khắc nghiệt, thiếu cảm thông.',
    reversedMeaning: 'Cay nghiệt quá mức, cô lập bản thân.',
    warning: 'Sự thật quan trọng, nhưng cách nói cũng quan trọng không kém.',
    element: 'Air',
    planet: 'Saturn',
    zodiac: 'Libra',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 63,
    name: 'King of Swords',
    number: 14,
    arcana: 'Minor',
    suit: 'Swords',
    imageEmoji: '👑',
    keywords: ['mental clarity', 'authority', 'truth', 'intellectual power', 'ethics'],
    generalMeaning: 'Rõ ràng tư duy, quyền lực, sự thật, sức mạnh trí tuệ, đạo đức.',
    loveMeaning: 'Người đàn ông lý trí, quyết định tình yêu dựa trên logic.',
    careerMeaning: 'Lãnh đạo bằng trí tuệ, ra quyết định công bằng, đạo đức.',
    familyMeaning: 'Người cha công bằng, dùng lý trí để dẫn dắt gia đình.',
    healthMeaning: 'Quyết định sức khỏe dựa trên phân tích lý trí.',
    futureMeaning: 'Sẽ cần tư duy rõ ràng và quyết định công bằng.',
    spiritualMeaning: 'Trí tuệ tối cao, sự thật tuyệt đối, đạo đức cao.',
    advice: 'Ra quyết định dựa trên lý trí và đạo đức, không cảm tính.',
    positiveMeaning: 'Công bằng, trí tuệ, quyền lực, đạo đức cao.',
    negativeMeaning: 'Lạnh lùng, độc đoán, quá lý trí, thiếu cảm xúc.',
    reversedMeaning: 'Lạm quyền, thao túng bằng lời nói, bất công.',
    warning: 'Quyền lực trí tuệ cần đi cùng với lòng nhân ái.',
    element: 'Air',
    planet: 'Uranus',
    zodiac: 'Libra',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  // MINOR ARCANA - PENTACLES (64-77)
  {
    id: 64,
    name: 'Ace of Pentacles',
    number: 1,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '🪙',
    keywords: ['prosperity', 'abundance', 'new opportunity', 'wealth', 'manifestation'],
    generalMeaning: 'Sự thịnh vượng, phong phú, cơ hội mới, tài lộc, biểu hiện.',
    loveMeaning: 'Cơ hội mới trong tình yêu, nền tảng vững chắc cho quan hệ.',
    careerMeaning: 'Cơ hội tài chính mới, khởi đầu công việc thịnh vượng.',
    familyMeaning: 'Sự ổn định tài chính gia đình, cơ hội mới.',
    healthMeaning: 'Nền tảng sức khỏe tốt, cơ hội cải thiện thể chất.',
    futureMeaning: 'Sẽ có cơ hội tài chính mới, sự thịnh vượng đến gần.',
    spiritualMeaning: 'Biểu hiện vật chất của phước lành tâm linh.',
    advice: 'Nắm bắt cơ hội tài chính khi nó xuất hiện.',
    positiveMeaning: 'Thịnh vượng, cơ hội, tài lộc, nền tảng vững.',
    negativeMeaning: 'Bỏ lỡ cơ hội, kế hoạch tài chính kém.',
    reversedMeaning: 'Cơ hội bị trì hoãn hoặc bỏ lỡ, thiếu kế hoạch.',
    warning: 'Xây dựng nền tảng vững chắc trước khi mở rộng.',
    element: 'Earth',
    planet: 'Venus',
    zodiac: 'Taurus',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 65,
    name: 'Two of Pentacles',
    number: 2,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '⚖️',
    keywords: ['balance', 'adaptability', 'multi-tasking', 'flexibility', 'juggling'],
    generalMeaning: 'Cân bằng, thích nghi, xử lý đa nhiệm, linh hoạt.',
    loveMeaning: 'Cân bằng giữa tình yêu và các trách nhiệm khác.',
    careerMeaning: 'Xử lý nhiều dự án cùng lúc, cần quản lý thời gian tốt.',
    familyMeaning: 'Cân bằng giữa công việc và gia đình.',
    healthMeaning: 'Cân bằng giữa nghỉ ngơi và hoạt động.',
    futureMeaning: 'Sẽ cần linh hoạt để cân bằng nhiều việc cùng lúc.',
    spiritualMeaning: 'Cân bằng giữa vật chất và tinh thần.',
    advice: 'Ưu tiên và quản lý thời gian hợp lý để giữ cân bằng.',
    positiveMeaning: 'Linh hoạt, thích nghi tốt, cân bằng cuộc sống.',
    negativeMeaning: 'Quá tải, mất cân bằng, không quản lý được.',
    reversedMeaning: 'Mất kiểm soát, quá nhiều việc cùng lúc.',
    warning: 'Đừng ôm đồm quá nhiều việc cùng lúc.',
    element: 'Earth',
    planet: 'Jupiter',
    zodiac: 'Capricorn',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 66,
    name: 'Three of Pentacles',
    number: 3,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '🔨',
    keywords: ['collaboration', 'teamwork', 'learning', 'apprenticeship', 'skill building'],
    generalMeaning: 'Hợp tác, làm việc nhóm, học hỏi, học nghề, xây dựng kỹ năng.',
    loveMeaning: 'Xây dựng quan hệ cùng nhau, hợp tác trong tình yêu.',
    careerMeaning: 'Làm việc nhóm hiệu quả, học hỏi từ đồng nghiệp.',
    familyMeaning: 'Hợp tác gia đình để đạt mục tiêu chung.',
    healthMeaning: 'Hợp tác với bác sĩ, chuyên gia để cải thiện sức khỏe.',
    futureMeaning: 'Sẽ có cơ hội hợp tác và học hỏi kỹ năng mới.',
    spiritualMeaning: 'Học hỏi từ cộng đồng tâm linh, chia sẻ tri thức.',
    advice: 'Hợp tác với người khác để đạt kết quả tốt hơn.',
    positiveMeaning: 'Hợp tác tốt, kỹ năng phát triển, công nhận từ nhóm.',
    negativeMeaning: 'Thiếu hợp tác, xung đột trong nhóm.',
    reversedMeaning: 'Làm việc nhóm kém hiệu quả, thiếu kỹ năng.',
    warning: 'Không ai thành công một mình, hợp tác là chìa khóa.',
    element: 'Earth',
    planet: 'Mars',
    zodiac: 'Capricorn',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 67,
    name: 'Four of Pentacles',
    number: 4,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '🔒',
    keywords: ['security', 'stability', 'control', 'possessiveness', 'conservatism'],
    generalMeaning: 'An toàn, ổn định, kiểm soát, sở hữu, bảo thủ.',
    loveMeaning: 'Bám giữ chặt tình yêu, sợ mất mát, cần buông lỏng.',
    careerMeaning: 'Bảo vệ tài sản công việc, có thể quá bảo thủ.',
    familyMeaning: 'Kiểm soát tài chính gia đình, đôi khi quá chặt chẽ.',
    healthMeaning: 'Lo lắng về việc mất kiểm soát sức khỏe.',
    futureMeaning: 'Cần cân bằng giữa an toàn và sự cởi mở.',
    spiritualMeaning: 'Bám víu vào vật chất, cần buông bỏ để phát triển.',
    advice: 'Đừng bám giữ quá chặt, học cách chia sẻ và buông bỏ.',
    positiveMeaning: 'An toàn tài chính, ổn định, có kế hoạch tốt.',
    negativeMeaning: 'Tham lam, ích kỷ, sợ chia sẻ, cô lập.',
    reversedMeaning: 'Buông bỏ kiểm soát, chia sẻ nhiều hơn, cởi mở.',
    warning: 'Kiểm soát quá mức sẽ khiến bạn cô đơn.',
    element: 'Earth',
    planet: 'Sun',
    zodiac: 'Capricorn',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 68,
    name: 'Five of Pentacles',
    number: 5,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '🥶',
    keywords: ['hardship', 'poverty', 'loss', 'abandonment', 'isolation'],
    generalMeaning: 'Khó khăn, nghèo khó, mất mát, bị bỏ rơi, cô lập.',
    loveMeaning: 'Cảm thấy cô đơn trong tình yêu, thiếu sự hỗ trợ.',
    careerMeaning: 'Khó khăn tài chính, mất việc, cần tìm sự giúp đỡ.',
    familyMeaning: 'Khó khăn gia đình, cảm giác bị bỏ rơi.',
    healthMeaning: 'Sức khỏe suy yếu do thiếu chăm sóc, cần hỗ trợ.',
    futureMeaning: 'Thời kỳ khó khăn, nhưng sự giúp đỡ ở gần hơn bạn nghĩ.',
    spiritualMeaning: 'Cảm giác bị bỏ rơi tâm linh, cần tìm lại niềm tin.',
    advice: 'Đừng ngại tìm kiếm sự giúp đỡ, bạn không đơn độc.',
    positiveMeaning: 'Vượt qua khó khăn với sự hỗ trợ từ người khác.',
    negativeMeaning: 'Nghèo khó kéo dài, cô lập, tuyệt vọng.',
    reversedMeaning: 'Bắt đầu hồi phục, tìm được sự giúp đỡ.',
    warning: 'Sự giúp đỡ luôn ở gần, đừng ngại tìm kiếm nó.',
    element: 'Earth',
    planet: 'Mercury',
    zodiac: 'Taurus',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 69,
    name: 'Six of Pentacles',
    number: 6,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '🤲',
    keywords: ['generosity', 'charity', 'fairness', 'abundance', 'giving and receiving'],
    generalMeaning: 'Rộng lượng, từ thiện, công bằng, phong phú, cho và nhận.',
    loveMeaning: 'Cho và nhận cân bằng trong tình yêu, sự hào phóng.',
    careerMeaning: 'Chia sẻ thành công, giúp đỡ đồng nghiệp, công bằng.',
    familyMeaning: 'Chia sẻ tài nguyên gia đình một cách công bằng.',
    healthMeaning: 'Nhận được sự chăm sóc, hoặc chăm sóc người khác.',
    futureMeaning: 'Sẽ có sự trao đổi công bằng, hào phóng.',
    spiritualMeaning: 'Cho đi để nhận lại, luật nhân quả tâm linh.',
    advice: 'Hào phóng với người khác, nhưng cũng cho phép mình nhận.',
    positiveMeaning: 'Hào phóng, công bằng, chia sẻ, phong phú.',
    negativeMeaning: 'Cho đi không công bằng, kiểm soát qua tiền bạc.',
    reversedMeaning: 'Nợ nần, mất cân bằng cho-nhận, ích kỷ.',
    warning: 'Sự hào phóng thật sự không mong đợi đền đáp.',
    element: 'Earth',
    planet: 'Moon',
    zodiac: 'Taurus',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 70,
    name: 'Seven of Pentacles',
    number: 7,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '🌱',
    keywords: ['assessment', 'effort', 'patience', 'waiting', 'long-term view'],
    generalMeaning: 'Đánh giá, nỗ lực, kiên nhẫn, chờ đợi, tầm nhìn dài hạn.',
    loveMeaning: 'Đánh giá lại đầu tư trong tình yêu, kiên nhẫn chờ kết quả.',
    careerMeaning: 'Đánh giá tiến độ dự án, kiên nhẫn chờ thành quả.',
    familyMeaning: 'Đánh giá nỗ lực đã bỏ ra cho gia đình.',
    healthMeaning: 'Kiên nhẫn với quá trình hồi phục sức khỏe.',
    futureMeaning: 'Cần kiên nhẫn, kết quả sẽ đến theo thời gian.',
    spiritualMeaning: 'Đánh giá con đường tâm linh, kiên nhẫn phát triển.',
    advice: 'Kiên nhẫn, thành quả cần thời gian để chín muồi.',
    positiveMeaning: 'Kiên nhẫn, đánh giá đúng, tầm nhìn dài hạn.',
    negativeMeaning: 'Thiếu kiên nhẫn, bỏ cuộc quá sớm, lãng phí nỗ lực.',
    reversedMeaning: 'Nóng vội, không đánh giá đúng tình hình.',
    warning: 'Đừng bỏ cuộc ngay trước khi gặt hái thành quả.',
    element: 'Earth',
    planet: 'Saturn',
    zodiac: 'Taurus',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 71,
    name: 'Eight of Pentacles',
    number: 8,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '🛠️',
    keywords: ['apprenticeship', 'learning', 'skill', 'mastery', 'dedication'],
    generalMeaning: 'Học nghề, học hỏi, kỹ năng, thành thạo, tận tâm.',
    loveMeaning: 'Nỗ lực xây dựng quan hệ, học cách yêu thương tốt hơn.',
    careerMeaning: 'Học hỏi kỹ năng mới, tận tâm với công việc.',
    familyMeaning: 'Dạy dỗ con cái, truyền đạt kỹ năng cho gia đình.',
    healthMeaning: 'Học cách chăm sóc sức khỏe tốt hơn qua thực hành.',
    futureMeaning: 'Sự tận tâm học hỏi sẽ mang lại thành thạo.',
    spiritualMeaning: 'Tận tâm rèn luyện con đường tâm linh.',
    advice: 'Tập trung rèn luyện kỹ năng, thành thạo cần thời gian.',
    positiveMeaning: 'Tận tâm, kỹ năng phát triển, chăm chỉ.',
    negativeMeaning: 'Làm việc qua loa, thiếu tập trung, chán nản.',
    reversedMeaning: 'Thiếu động lực học hỏi, kỹ năng trì trệ.',
    warning: 'Thành thạo đến từ sự luyện tập kiên trì, không phải một sớm một chiều.',
    element: 'Earth',
    planet: 'Sun',
    zodiac: 'Virgo',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 72,
    name: 'Nine of Pentacles',
    number: 9,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '🌹',
    keywords: ['independence', 'abundance', 'self-sufficiency', 'luxury', 'accomplishment'],
    generalMeaning: 'Độc lập, phong phú, tự chủ, sang trọng, thành tựu.',
    loveMeaning: 'Yêu bản thân trước, độc lập trong tình yêu.',
    careerMeaning: 'Thành công tự lực, độc lập tài chính.',
    familyMeaning: 'Tự chủ trong gia đình, thành tựu cá nhân.',
    healthMeaning: 'Chăm sóc bản thân tốt, tận hưởng cuộc sống lành mạnh.',
    futureMeaning: 'Sẽ đạt được sự độc lập và phong phú.',
    spiritualMeaning: 'Tự chủ tâm linh, hài lòng với chính mình.',
    advice: 'Tận hưởng thành quả lao động của chính bạn.',
    positiveMeaning: 'Độc lập, phong phú, tự chủ, hài lòng.',
    negativeMeaning: 'Cô lập quá mức, phô trương, xa cách người khác.',
    reversedMeaning: 'Phụ thuộc quá nhiều, mất tự chủ tài chính.',
    warning: 'Độc lập là tốt, nhưng đừng để nó trở thành cô lập.',
    element: 'Earth',
    planet: 'Venus',
    zodiac: 'Virgo',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 73,
    name: 'Ten of Pentacles',
    number: 10,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '🏰',
    keywords: ['wealth', 'inheritance', 'family', 'legacy', 'long-term success'],
    generalMeaning: 'Giàu có, thừa kế, gia đình, di sản, thành công lâu dài.',
    loveMeaning: 'Hôn nhân bền vững, xây dựng gia đình lâu dài.',
    careerMeaning: 'Thành công lâu dài, ổn định tài chính vững chắc.',
    familyMeaning: 'Di sản gia đình, sự giàu có được truyền qua thế hệ.',
    healthMeaning: 'Sức khỏe ổn định lâu dài, nền tảng tốt.',
    futureMeaning: 'Sẽ có sự thịnh vượng và ổn định lâu dài.',
    spiritualMeaning: 'Di sản tâm linh, truyền lại trí tuệ cho thế hệ sau.',
    advice: 'Xây dựng nền tảng vững chắc cho tương lai lâu dài.',
    positiveMeaning: 'Giàu có, ổn định, di sản, gia đình vững mạnh.',
    negativeMeaning: 'Tranh chấp thừa kế, bất ổn tài chính gia đình.',
    reversedMeaning: 'Mất mát tài sản gia đình, xung đột thừa kế.',
    warning: 'Sự giàu có thật sự nằm ở các mối quan hệ được vun đắp.',
    element: 'Earth',
    planet: 'Mercury',
    zodiac: 'Virgo',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 74,
    name: 'Page of Pentacles',
    number: 11,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '🌾',
    keywords: ['diligence', 'studiousness', 'ambition', 'learning', 'new venture'],
    generalMeaning: 'Chăm chỉ, ham học hỏi, tham vọng, học tập, dự án mới.',
    loveMeaning: 'Cam kết nghiêm túc, xây dựng nền tảng cho tình yêu.',
    careerMeaning: 'Cơ hội học tập mới, khởi đầu sự nghiệp đầy tham vọng.',
    familyMeaning: 'Con cái chăm chỉ, ham học hỏi trong gia đình.',
    healthMeaning: 'Bắt đầu thói quen lành mạnh mới một cách chăm chỉ.',
    futureMeaning: 'Sẽ có cơ hội học tập và phát triển mới.',
    spiritualMeaning: 'Khởi đầu hành trình học hỏi tâm linh nghiêm túc.',
    advice: 'Chăm chỉ học hỏi, đặt nền móng vững chắc cho tương lai.',
    positiveMeaning: 'Chăm chỉ, tham vọng, học hỏi tốt, thực tế.',
    negativeMeaning: 'Thiếu tập trung, kế hoạch không thực tế.',
    reversedMeaning: 'Trì hoãn học tập, thiếu động lực, bỏ cuộc.',
    warning: 'Tham vọng cần đi cùng với sự kiên trì thực tế.',
    element: 'Earth',
    planet: 'Mars',
    zodiac: 'Capricorn',
    difficulty: 1,
    memoryLevel: 'easy',
  },
  {
    id: 75,
    name: 'Knight of Pentacles',
    number: 12,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '🐴',
    keywords: ['reliability', 'efficiency', 'responsibility', 'hard work', 'routine'],
    generalMeaning: 'Đáng tin cậy, hiệu quả, trách nhiệm, chăm chỉ, thói quen.',
    loveMeaning: 'Người yêu đáng tin cậy, ổn định, cam kết lâu dài.',
    careerMeaning: 'Làm việc chăm chỉ, đáng tin cậy, hiệu quả cao.',
    familyMeaning: 'Thành viên đáng tin cậy, có trách nhiệm với gia đình.',
    healthMeaning: 'Duy trì thói quen sức khỏe đều đặn, kỷ luật.',
    futureMeaning: 'Sẽ đạt được kết quả nhờ sự kiên trì và trách nhiệm.',
    spiritualMeaning: 'Kỷ luật trong thực hành tâm linh hàng ngày.',
    advice: 'Kiên trì với thói quen tốt, đáng tin cậy trong mọi việc.',
    positiveMeaning: 'Đáng tin cậy, chăm chỉ, có trách nhiệm, ổn định.',
    negativeMeaning: 'Cứng nhắc, nhàm chán, sợ thay đổi, trì trệ.',
    reversedMeaning: 'Lười biếng, thiếu trách nhiệm, trì hoãn công việc.',
    warning: 'Sự ổn định là tốt, nhưng đừng ngại thử điều mới.',
    element: 'Earth',
    planet: 'Sun',
    zodiac: 'Virgo',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 76,
    name: 'Queen of Pentacles',
    number: 13,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '👑',
    keywords: ['practicality', 'creature comforts', 'financial security', 'nurturing', 'down-to-earth'],
    generalMeaning: 'Thực tế, tiện nghi, an toàn tài chính, nuôi dưỡng, giản dị.',
    loveMeaning: 'Người phụ nữ thực tế, chăm sóc chu đáo cho gia đình.',
    careerMeaning: 'Quản lý tài chính khéo léo, kinh doanh thực tế.',
    familyMeaning: 'Người mẹ chăm sóc chu đáo, tạo tổ ấm thoải mái.',
    healthMeaning: 'Chăm sóc sức khỏe thực tế, cân bằng cuộc sống.',
    futureMeaning: 'Sẽ có sự an toàn tài chính và cuộc sống thoải mái.',
    spiritualMeaning: 'Kết nối tâm linh với thiên nhiên và vật chất.',
    advice: 'Chăm sóc bản thân và người khác một cách thực tế.',
    positiveMeaning: 'Thực tế, nuôi dưỡng, an toàn tài chính, ấm áp.',
    negativeMeaning: 'Quá vật chất, lo lắng quá mức về tài chính.',
    reversedMeaning: 'Bỏ bê bản thân, mất cân bằng công việc-gia đình.',
    warning: 'Chăm sóc người khác nhưng đừng quên chăm sóc bản thân.',
    element: 'Earth',
    planet: 'Earth',
    zodiac: 'Taurus',
    difficulty: 2,
    memoryLevel: 'medium',
  },
  {
    id: 77,
    name: 'King of Pentacles',
    number: 14,
    arcana: 'Minor',
    suit: 'Pentacles',
    imageEmoji: '👑',
    keywords: ['wealth', 'success', 'leadership', 'abundance', 'business acumen'],
    generalMeaning: 'Giàu có, thành công, lãnh đạo, phong phú, tài kinh doanh.',
    loveMeaning: 'Người đàn ông thành đạt, mang lại sự ổn định cho tình yêu.',
    careerMeaning: 'Thành công kinh doanh, lãnh đạo tài ba, giàu kinh nghiệm.',
    familyMeaning: 'Người cha thành đạt, trụ cột tài chính gia đình.',
    healthMeaning: 'Sức khỏe ổn định nhờ lối sống có kỷ luật.',
    futureMeaning: 'Sẽ đạt được thành công và sự giàu có bền vững.',
    spiritualMeaning: 'Làm chủ hoàn toàn khía cạnh vật chất của cuộc sống.',
    advice: 'Sử dụng thành công của bạn để giúp đỡ người khác.',
    positiveMeaning: 'Giàu có, thành công, lãnh đạo, hào phóng.',
    negativeMeaning: 'Tham lam, chỉ coi trọng vật chất, độc đoán.',
    reversedMeaning: 'Thất bại tài chính, quản lý kém, tham lam.',
    warning: 'Thành công thật sự không chỉ đo bằng của cải vật chất.',
    element: 'Earth',
    planet: 'Earth',
    zodiac: 'Taurus',
    difficulty: 1,
    memoryLevel: 'easy',
  },
];

